mkmccarty/TokenTimeBoostBot

main.go
src/boost/boost.go

Added ability to mark a farmer as umboosted.

Changes made to mark a farmer as unboosted

---

doc/HowToBoostBot.md

Updated the How To Boost Bot document.

Mkmccarty patch 1

---

go.mod
go.sum
main.go
src/boost/boost.go

Updated go-openai dependency to v1.20.3.
Updated googleapis/api and googleapis/rpc dependencies to latest versions for grpc compatibility.
Reformatted commit message output for clarity.

chore: update dependencies to latest versions

---

main.go

- Updated the description of the mission-duration option in the application command to include multiple mission durations. 
This change was made to provide more flexibility and clarity for users when inputting mission durations.

feat: Update description for mission-duration option

---

main.go
src/farmerstate/farmerstate.go

Added missionJSON string with ship data including name, art, and duration. Updated missionData struct variable with ship information.
feat: Update missionData struct initialization in init function
Unmarshalled missionJSON data into the mis variable in the init function for better data handling.
feat: Add chain option for extended mission display
Added the chain option for showing extended missions. Modified logic to handle chainExtended status and update launch history accordingly. 
feat: Calculate extended duration based on FTL level
Calculated extended duration based on FTL level percentage and updated the display with appropriate information. Added chain launch time if extended mission option is selected.

feat: Add missionJSON with ship data and update missionData variable

---

main.go
src/farmerstate/farmerstate.go

This commit introduces the shipData struct with Name, Art, and Duration
fields. The missionData struct now contains a slice of shipData objects
instead of anonymous structs. This change improves code readability and
maintains consistency throughout the codebase.

feat: Add shipData struct and refactor missionData to use it

---

main.go

- Added "All Stars Club" and "Starfleet Commander" to the list of mission ships
- Adjusted logic to handle special cases for "All Stars Club" and "Starfleet Commander"
- Updated ship name display to differentiate between ships and special mission groups

refactor: Update mission ships and ship names for All Stars Club and Starfleet Commander

---

main.go

Update the response type to ChannelMessageWithSource for better interaction
handling. This ensures the response is appropriately displayed to the user.

refactor: Change response type to ChannelMessageWithSource

---

go.sum

Removed unnecessary dependencies from the project to clean up the codebase and improve maintainability.

refactor: remove unnecessary dependencies

---

src/boost/boost.go
src/boost/boost_datastore.go
src/boost/boost_wish.go

Refactored boost package files to separate datastore functionality into
its own file and improve code organization. Removed unused imports and
variables to clean up the codebase.

refactor(boost): Refactor boost package files

---

main.go
src/track/track.go
src/track/track_handlers.go

Refactored the code to include response handling for token tracking interactions. 
Added response type for interaction responses to ensure correct behavior.

feat: Update token tracking response handling

---

main.go
src/boost/boost.go
src/track/track.go
src/track/track_handlers.go

Added constants for token tracking
Included new fields for tracking linked tokens and received tokens
Improved calculations for sum of token values sent and received
Adjusted token tracking display for sent and received tokens

feat: Update token tracking with new fields and calculations

---

src/track/track.go

The changes enable displaying and editing farmed token time in the message.
The "Farmed" section now includes detailed information about farmed tokens.

feat(track): add functionality to display and edit farmed token time in message

---

go.mod
go.sum
main.go
src/boost/boost_handlers.go
src/track/track.go
src/track/track_handlers.go

Updated the message components in the track handlers to improve efficiency
and accuracy. Replaced repeated component assignments with references for
getTokenValComponents. This ensures consistency and reduces redundancy in
code.

feat: Update message components in track handlers

---

main.go
src/track/track.go
src/track/track_handlers.go

Added a new function `ReactionAdd` to handle reactions added to messages.
This function updates the message content and components based on the reaction.
Also implemented removal of received token values when removing a reaction.

feat: Add handling for reactions to track message updates

---

main.go

Add new slash command for setting various bot settings including enabling/disabling debug logging. Implemented debug logging to output interaction details if debug mode is enabled.

feat: Add bot settings command and debug logging capability

---

main.go

Extracted the assignment of userId based on GuildID from main function for better
readability and maintainability. Ensures correct userId is assigned for further
processing.

refactor: Refactor userId assignment in componentHandlers

---

main.go

Removed the unnecessary tokenWant variable and directly set tokenWant value.
Refactored token setting logic based on whether guestName is present or not.
Removed redundant calls to AddBoostTokens function.

feat: Refactor token handling logic in main.go

---

main.go
src/track/track.go
src/track/track_handlers.go

- Refactor conditional display for "Contract Channel" information
- Update token value formatting to 3 decimal places for precision

refactor: Improve token tracking display formatting

---

src/boost/boost.go
src/boost/boost_reactions.go
src/boost/boost_speedrun.go

- Update message format to include channel ping
- Track sender of received tokens
- Track recipient of sent tokens
- Record time when each token is farmed

feat: Enhance chicken runs tracking

---

main.go
src/track/track.go
src/track/track_handlers.go

Add log statements for ContractTokenMessage function to log user ID, kind, count, and actorUserID.
Add log statement for Token-Reaction function to log emojiName, name, and userID.

feat: Add logging for ContractTokenMessage and Token-Reaction functions

---

src/boost/boost_slashcalctval.go

Refactor calculateTokenValue function to accept a boolean for details. 
Update HandleContractCalcContractTvalCommand to handle the details option 
provided in the command. Display individual token values if details is true.

feat: Enhance token value calculation with details option

---

src/boost/boost_speedrun.go

Updated the code to append the TokenSentName and TokensFarmedTime arrays
with relevant user IDs and timestamps for tracking purposes. This
functionality enhances the ability to monitor token transactions and
farming activities efficiently.

feat: Add functionality to track TokenSentName and TokensFarmedTime

---

src/track/track.go
src/track/track_handlers.go
src/track/track_slashcmd.go

Changed the return types and content in tokenTrackingTrack, tokenTrackingAdjustTime,
and other functions to return *discordgo.MessageSend for message embedding, improving
the display of token tracking information.

refactor: Modify return types and content for better message embedding

---

main.go
src/boost/boost.go
src/boost/boost_draw.go
src/boost/boost_reactions.go
src/boost/boost_sink.go

Added the ability to volunteer as a token sink for a contract using a new
slash command and reaction handling. This allows users to claim the token sink
position in a contract.

feat: Add volunteer sink functionality

---

src/boost/boost.go

Added a GlobalName field to the EggFarmer struct to track the global name of the user across contracts.

feat: Add GlobalName field to EggFarmer struct

---

main.go
src/boost/boost.go

Update mentions in several functions to use User mention instead of 
Member mention to ensure correct user information is displayed. This 
improves consistency and accuracy in displaying user information.

feat: Update mentions to use User mention instead of Member mention

---

src/boost/boost_speedrun.go

Add a reaction to indicate when the Sink starts to kick users. Also, prompt
users to react with 💃 to move to the next tango.

chore: Update kick reaction in speedrun process

---

src/boost/boost_speedrun.go

Update the message for kicking users in the speedrun to be more clear and concise.

feat: Update message for kicking users in speedrun

---

src/boost/boost_reactions.go
src/boost/boost_speedrun.go

Update the message for Sink kicks to indicate moving to advance the maketango
by reacting with 💃.

refactor: Update reaction message for Sink kicks

---

src/notok/notok_slashcmd.go

Add min value constraint of 20.0 and max value constraint of 250.0 to the
`prompt` option in the SlashFunCommand function for the /fun command.

feat: Add min and max value constraints to prompt in SlashFunCommand

---

main.go
src/boost/boost_slashcalctval.go
src/track/track.go

feat: Update tracking embed to include footer with detailed tracking information and instructions for accurate values.

refactor: Add footer with tracking information

---

src/boost/boost_draw.go
src/boost/boost_speedrun.go

- Update boost message with new formatting for clarity and consistency.
- Add new emojis to improve visual representation of actions.
- Adjust description of boost token process for better understanding.

refactor(boost): Update boost message formatting

---

main.go
src/boost/boost.go

Refactored the implementation of the AddBoostTokens function in the boost.go
file to accept an InteractionCreate object instead of individual parameters.
This change simplifies the function signature and enhances readability.

feat: Refactor boost.AddBoostTokens implementation

---

src/boost/boost_slashcalctval.go
src/track/track.go

Adjust the format for displaying token values in the tracking and calculation
sections for better clarity and accuracy.

feat: Update token value display format in tracking and calculation

---

src/boost/boost_speedrun.go

Refactored code to improve efficiency when tracking players who have not run
chickens yet. Removed unnecessary code and optimized loop for better
performance.

feat: Optimize chicken run tracking algorithm

---

src/boost/boost.go
src/boost/boost_speedrun.go

Added a check to delete the Chicken Run Check message when all players have
run chickens. Also updated display of remaining users who haven't run yet.

feat: Add functionality to delete Chicken Run Check message

---

main.go
src/boost/boost_slashcmd.go
src/track/track_slashcmd.go

Update token removal logic to handle cases where the token index is invalid.
Return appropriate messages based on the token type and index provided.

feat: Improve handling of token removal in /token-remove cmd

---

main.go
src/launch/launch_slashcmd.go

Refactored the code to handle user ID based on GuildID presence and updated the
selection of primary and secondary mission ships based on user ID instead of
Member User ID to improve consistency and accuracy.

refactor: Update user ID handling and mission ship selection

---

main.go

Move some commands to a new globalCommand section so its easy to make commands available to DM

refactor: Implement global slash commands in BoostBot Home Guild

---

src/boost/boost_speedrun.go

Improve formatting of the speedrun reactions message to include the Speedrun
Starter user and provide clearer instructions for the process.

feat: Enhance speedrun reactions message formatting

---

main.go
src/boost/boost_slashcalctval.go
src/track/track.go

Calculate token values directly in the loop instead of accessing the array
index to improve code readability and performance.

refactor: Update token value calculations in getTokenTrackingEmbed function

---

src/boost/boost.go
src/boost/boost_draw.go
src/boost/boost_reactions.go

Removed almost duplicate structure called EggFarmer which wasn't used much

feat: Refactor AddFarmerToContract to AddBoosterToContract

---

main.go
src/tasks/tasks.go

- Moved logic to get the EI contract data out of the main.go source into its own sources

refactor: Refactor fetching Egg Inc contract data handling and updating logic

---

src/boost/boost.go
src/boost/boost_admin.go

- Only allow the command if the user is in the admin list
- Display an error message if unauthorized
- Implement adminUsers slice in HandleAdminContractFinish

feat(boost): Add admin authorization check before finishing contract

---

src/tasks/tasks.go

Changed the cron job schedule to use the gocron library for more
flexibility and readability. Added a new task at 9:05:00 to download
Egg, Inc. contracts.

feat(tasks): Update cron job schedule

---

go.mod
go.sum
src/boost/boost_test.go

Added github.com/gorilla/mux v1.8.1 and github.com/ewohltman/discordgo-mock 
v0.0.11 to the dependencies in go.mod and go.sum.

feat: Added github.com/gorilla/mux v1.8.1 and github.com/ewohltman/discordgo-mock v0.0.11

---

src/boost/boost.go

Change notification message to correctly prompt users to send tokens
to the volunteer sink.

feat(boost): update notification message for sending tokens

---

main.go
src/boost/boost.go
src/boost/boost_reactions.go
src/boost/boost_speedrun.go
src/notok/notok.go

Add a 4️⃣ to 🔟 reaction to the boost list message instead of a 0️⃣.

feat: Update boost list message with the correct number of reactions

---

src/boost/boost.go

Add new fields to the contract struct in the CreateContract function to include Name, Description, EggName, TargetAmount, qTargetAmount, ChickenRunCooldownMinutes, and MinutesPerToken. Update the values accordingly.

feat: Update contract fields in CreateContract function

---

src/boost/boost_draw.go

Changed the output format of the contract information to include the contract name in parentheses and removed unnecessary URL in the Coordinator section. These changes improve the readability of the contract details displayed.

refactor: Update contract output format for better readability

---

src/boost/boost_help.go

Changed the logic to determine the user ID based on guild existence in
order to properly fetch help information for the user.

refactor: Update user ID handling in HandleHelpCommand

---

src/boost/boost_speedrun.go

Added a step to run chickens on the player's own farm if SelfRuns flag is
true in the contract data.

feat: Add step to run chickens on own farm

---

src/tasks/tasks.go

Removed the unnecessary question mark from the egg,inc contracts URL to
ensure proper functionality.

fix: Remove unnecessary question mark from egg,inc url

---

src/launch/launch_slashcmd.go

Added the ability to set a Faster Missions multiplier in the launch command.
Default is 1x, with options for 2x, 3x, and 4x to adjust mission speeds.

feat: Implement option for Faster Missions multiplier

---

src/tasks/tasks.go

Added more minute intervals to the list of times at which the cron job can
execute for better scheduling accuracy.

refactor: Add more minute intervals to cron job execution

---

src/boost/boost.go
src/boost/boost_slashcmd.go

In boost.go, removed the RemoveContractBooster function and updated
related functions to perform booster removal task. This change streamlines
booster removal process and enhances code readability.

refactor: Modify contract booster removal function

---

src/boost/boost.go

Simplify the logic for removing a booster from a contract by reordering steps
and handling edge cases more effectively. Update related state changes and
notifications accordingly.

refactor: Improve contract booster removal logic

---

main.go

Refactored the interaction response handling by replacing direct response
calls with FollowupMessageCreate for better code organization and clarity.

feat: Refactor interaction response handling in main.go

---

src/launch/launch_slashcmd.go

Refactor the mission display to show only the relevant information for each mission
including the arrival time and FTL level. Also, add instructions for missions
arriving after Sunday events and within dubcap.

feat: Improve mission display in launch command

---

main.go

Removed unnecessary else block in joinContract function that was causing
redundant code and potential confusion about code flow.

feat: Remove unnecessary else block in joinContract function

---

main.go
src/launch/launch_slashcmd.go
src/track/track.go
src/track/track_handlers.go
src/track/track_slashcmd.go

The if condition for checking token edit status in the syncTokenTracking
function was redundant and has been removed to simplify the logic.

refactor: Remove unnecessary boolean check on token edit status

---

src/boost/boost.go
src/boost/boost_reactions.go
src/boost/boost_speedrun.go

Added the `ChickenRunEmoji` field to the `Contract` struct to store the chicken
run emoji. The emoji is now retrieved and stored using the
`findBoostBotGuildEmoji` function.

feat: Add chicken run emoji to Contract struct

---

src/launch/launch_slashcmd.go

Refactored the FollowupMessageCreate function to only include message
embedding if the instruction string is not empty. This change enhances the
appearance of the embedded message for better user experience.

feat: Improved handling of message embedding

---

src/boost/boost.go
src/boost/boost_draw.go
src/boost/boost_reactions.go

Update the boost icon in various messages with a dynamic value based on
boostIcon variable. This change provides flexibility to change the boost
icon easily across the application.

feat(boost): Update boost icon with dynamic value

---

src/track/track_slashcmd.go

Refactored the code to improve readability and commented out unnecessary
conditional statement for better understanding of the logic behind.

feat: Improve clarity in HandleTokenCommand function

---

src/boost/boost_draw.go
src/boost/boost_reactions.go
src/boost/boost_speedrun.go

- Add timestamp to indicate when a user is ready for chicken runs
- Include chicken emoji and message when user is ready
- Trigger redraw to update boost list when changes occur

feat: Update boost reactions to include chicken run indication

---

src/launch/launch_slashcmd.go

When the message size exceeds 1500 characters, limit the display size and
show a warning to reduce missions or disable the chain option. Also, include
changes to handle the normal and header strings and prevent display issues.

feat: Limit display size and show warning if exceeded

---

src/notok/notok.go
src/notok/notok_slashcmd.go

Return values changed to include error handling in wishImage and getLetMeOutString
functions for better error reporting and handling.

feat: Update return types in wishImage and getLetMeOutString functions

---

src/boost/boost.go
src/boost/boost_draw.go

Improve the check for contract.BoostPosition, ensuring it is not -1 before
attempting to access the booster. Also, avoid unnecessary booster state
modification and time update when contract.BoostPosition is -1.

feat: Improve booster handling in RemoveContractBoosterByMention function

---

src/boost/boost_draw.go

Changed the join order message formatting in the boost list display for better readability.

feat: Update boost list display message

---

src/launch/launch_slashcmd.go

Removed unnecessary comment and field in HandleLaunchHelper function to improve code readability.

build: Remove unnecessary comment and field in HandleLaunchHelper

---

src/boost/boost.go
src/boost/boost_draw.go

Fixes fields in the Contract struct in boost.go to include PlannedStartTime and ActualStartTime for better tracking. Adjusts CoopSize, LengthInSeconds, BoostOrder, BoostVoting, BoostPosition, State, StartTime, EndTime to align with changes in the code.

feat: Adjust contract struct in boost.go

---

src/boost/boost_wish.go
src/notok/notok.go

Add contract descriptions to various prompts and responses for more context
and immersion in the gameplay experience. This includes adding descriptions
to chicken role prompts, letter generation, and wish fulfillment actions.

feat: Enhance functionality of contract descriptions

---

src/boost/boost_wish.go
src/notok/notok.go

Adjusted the wish generation in wishGemini to include the mention's wish, replace
"widget" with "token", and suggest an additional consideration for the response.

feat: Improve wishGemini wish generation

---

go.mod
go.sum
src/boost/boost_slashcalctval.go

Added functionality to render a table displaying the details of sent and received tokens in a more organized manner. Utilized the tablewriter package for formatting the output.

feat: Added table rendering for sent and received tokens

---

src/boost/boost_slashcalctval.go

Improve the styling of the table in the calculateTokenValue function to enhance readability and presentation. Set center separator, column separator, row separator, header line, table padding, and remove whitespace for a cleaner look.

refactor(table): improve table styling in calculateTokenValue function

---

src/boost/boost.go
src/boost/boost_draw.go

Add lastDrawTime field to Contract struct to track the last time the contract
was drawn. This field is updated in the DrawBoostList function.

feat: Add lastDrawTime field to Contract struct

---

main.go
src/launch/launch_slashcmd.go
src/tasks/tasks.go

- Calculate chain launch time based on extended duration
- Adjust chain launch time for faster mission multipliers
- Improve handling of fast duration timing
- Refactor code for better readability and accuracy

feat: Improve chain string calculation and handling

---

src/boost/boost.go
src/boost/boost_speedrun.go
src/track/track.go

feat: Add logging for archiving contracts and purging tracker data

refactor: Update user identification in boost_speedrun and boost.go

---

src/boost/boost_admin.go

Adds new user IDs to the adminUsers list for increased access control.

refactor: Update adminUsers list with additional user IDs

---

src/boost/boost_admin.go
src/boost/boost_teamwork.go
src/farmerstate/farmerstate.go

Fixed padding issue in navigation bar and improved overall design with new hover effects.

feat: Update navigation bar styling and add new hover effects

---

src/boost/boost.go
src/boost/boost_draw.go
src/boost/boost_reactions.go
src/boost/boost_wish.go
src/tasks/tasks.go

Update LastWishPrompt and LastInteractionTime fields in the Contract structure to
improve data consistency and tracking. Additionally, change the cron job
frequency for archiving contracts from daily to every 8 hours for better
management.

feat: Update LastWishPrompt and LastInteractionTime in Contract structure

---

main.go
src/boost/boost.go
src/boost/boost_estimate.go
src/boost/boost_slashcalctval.go

- Added new slash command for estimating time needed to complete a contract
- Handles both providing a contract ID and detecting current contract in channel

feat: Add slash command to estimate contract time

---

main.go
src/boost/boost_track.go
src/track/track_slashcmd.go

feat: Add TokenTimeBoostBot dependency to boost_track
feat: Add HandleTokenCommand to boost package
refactor: Update HandleTokenCommand to include contract ID param
refactor: Set duration based on contract in HandleTokenCommand

refactor: Change contract duration description to include linked contracts

---

src/boost/boost_teamwork.go
src/farmerstate/farmerstate.go

- Improved the contract status message display
- Added start time, estimated end time, and duration
- Refactored to use strings.Builder for better performance

refactor: Update contract status display message (#1234)

---

src/boost/boost_teamwork.go

Adds a new option in the command to evaluate Egg Inc contract values based
on an in-game name provided by the user.
build: Add evaluation message for specific einame

feat: Add option to evaluate Egg Inc contract by in-game name

---

main.go
src/boost/boost.go
src/boost/boost_admin.go
src/boost/boost_change.go
src/boost/boost_help.go
src/boost/boost_reactions.go
src/boost/boost_slashcmd.go
src/boost/boost_speedrun.go
src/tasks/tasks.go

refactor: Update parameters in creatorOfContract and HandleAdminContractFinish functions

refactor: Remove redundant code in CreateContract function

---

src/boost/boost_estimate.go

Change estimated time message format for speedrun or fastrun to include contract
name, ID, number of farmers, and required eggs.

feat: Update estimate response message format

---

src/boost/boost_estimate.go

- Update description to correctly reflect purpose
- Add interaction context and integrations for improved functionality

feat: Update GetSlashEstimateTime description and context

---

src/boost/boost.go
src/boost/boost_draw.go
src/boost/boost_slashcmd.go

Update message flags to suppress embeds for boosting interactions, ensuring a cleaner and improved user experience.

feat: Update message flags for boosting interactions

---

src/boost/boost.go
src/boost/boost_reactions.go
src/boost/boost_speedrun.go

Check if the booster is in BoostStateBoosted and has not run chickens before
setting ready state. Update message accordingly.

feat: Ensure boosters are ready for chicken runs before updating status

---

main.go
src/boost/boost.go
src/boost/boost_button_reactions.go
src/boost/boost_slashcmd.go
src/config/config.go

feat: Add test mode feature for contract creation
feat: Refactor contract reaction handling with new file and function

feat: Refactor user ID handling to a separate function

---

src/boost/boost_button_reactions.go
src/boost/boost_reactions.go
src/boost/boost_speedrun.go

The logic to indicate when a farmer is ready for chicken runs was incorrect and
has been fixed. The messaging for indicating readiness has also been updated
for accuracy.

fix: Fix logic error in indicating user ready for chicken runs and update messaging

---

src/boost/boost_draw.go

Completing the contract boosting process now displays a message indicating the
boosting has been completed successfully along with further instructions.

✨ Add completion message after contract boosting

---

src/version/version.go

Added Release, Version, and GitHash variables to version package.

✨ Add version metadata to the application 📦

---

go.mod
go.sum

Upgraded genproto to v0.0.0-20240708141625-4ad9e859172b.

✨ Upgrade genproto to the latest version

---

src/boost/boost_estimate.go

Update the estimated duration calculation and formatting for better
readability and accuracy.

✨ Refactor estimate time message handling

---

src/boost/contract.go

Default to always create a thread for new contracts. Check if bot has
permission to create public threads before creating one.

✨ Add functionality to create threads for contracts

---

src/boost/artifacts.go
src/boost/boost.go
src/boost/boost_draw.go
src/boost/boost_handlers.go
src/boost/contract.go
src/boost/stones.go
src/ei/ei_data.go

- Include global artifacts menu for coop boosters
- Update display for global coop artifacts
- Set default values for global artifact types in menu
- Handle global artifact overrides and contract artifacts

feat(boost): Update artifacts menu with global artifacts

---

src/boost/boost.go
src/boost/boost_handlers.go

function and simplify getBoostOrderString for ContractOrderELR.

refactor: Update description for ELR Order in getSignupContractSettings

---

src/track/track_handlers.go

This commit updates the interaction responses in HandleTokenDetails, 
HandleTokenSend, HandleTokenReceived, and HandleTokenComplete functions to 
use deferred message update with ephemeral messages. This change improves 
user experience by reducing loading time and only showing messages to the 
command issuer.

feat: Update interaction responses to use deferred message update and ephemeral messages

---

src/boost/stones.go

Show all stone variations in the report when generating a solo report,
including additional information about artifact slots if less than 3.

feat(boost): Improve stone variations for solo report

---

src/boost/boost_calctval.go

- Truncate user names longer than 12 characters with ellipsis for better
readability.

refactor(boost_calctval): Update name truncation to include ellipsis

---

src/boost/artifacts.go

Add Firework artifact with 5% earnings and Waterballoon artifact with 5% Unknown to the 
select menu options.

feat(boost): Add Firework and Waterballoon artifacts in select menu

---

src/boost/boost.go
src/boost/contract.go
src/ei/ei_data.go

Set contract Token emoji based on DiscordAppID and improve egg emoji retrieval for
given guild.

refactor: Update Token and Egg Emoji assignment logic

---

src/boost/boost_slashcmd.go

Updated the join command to handle multiple farmers and set tokens individually.
Added support to split multiple farmer names and set tokens accordingly.

feat: Handle multiple farmers in join command and set tokens individually

---

src/boost/boost.go
src/boost/boost_button_reactions.go
src/boost/boost_calctval.go
src/boost/boost_track.go
src/boost/state_banker.go
src/ei/ei_data.go
src/track/track.go
src/track/track_slashcmd.go

Changed the struct name from TokenUnitLog to ei.TokenUnitLog in multiple files to maintain consistency.

refactor(ei): Update struct name from TokenUnitLog to ei.TokenUnitLog

---

main.go
src/boost/boost_slashcmd.go
src/track/track_slashcmd.go

Renamed HandleTokenRemoveAutoComplete to
HandleTokenListAutoComplete for consistency.

feat: Update token autocompletion function names

---

src/boost/boost.go
src/boost/boost_button_reactions.go
src/boost/boost_calctval.go
src/boost/boost_handlers.go
src/boost/contract.go
src/boost/state_banker.go

Calculate token value from sent and received values
and update booster's token value accordingly.
Introduce Token Value based booster ordering along
with necessary adjustments in booster reorderings.

feat: Implement Token Value based booster ordering

---

src/boost/boost_handlers.go
src/boost/contract.go
src/config/config.go
src/ei/ei_data.go
src/launch/launch_slashcmd.go

This commit introduces the IsDevBot function to handle configuration checks
for the development bot.

refactor: Introduce IsDevBot function to handle configuration checks

---

src/boost/boost_handlers.go
src/ei/ei_data.go

Adds a struct to hold emoji data and a map for bot component emojis. Updates
functions to get bot component emojis and markdown format for emojis.

feat(botemoji): Add emoji data and map for bot components

---

src/boost/boost_teamwork.go

Updated the download coop status function to include an embed parameter for sending an embedded message when necessary.

feat: Improve embed handling in HandleTeamworkEvalCommand

---

src/boost/boost_draw.go

- Extract wanted elements around current booster
- Prioritize completion state over signup state
- Show early and late lists separately.

refactor: Handle showing boosted numbers efficiently

---

src/boost/artifacts.go
src/boost/stones.go
src/ei/ei_data.go

Removes unnecessary option mapping in the HandleArtifactCommand 
function. Eliminates unused contract checks to streamline command 
processing. Cleans up commented-out code for improved readability 
and maintainability.

refactor: simplify artifact command handling and clean up code

---

src/boost/dynamictokens.go
src/boost/dynamictokens_test.go

Refactor the dynamic token calculation by introducing a new 
`DynamicTokenData` struct to encapsulate related data. 
Implement a new function `calculateDynamicTokens` to handle 
the logic for calculating token boosts. Add unit tests to 
verify the functionality of the new calculation method. 
These changes improve code organization and maintainability

feat: refactor dynamic token calculation logic

---

src/boost/stones.go

Refactor the `DownloadCoopStatusStones` to improve the 
output handling for Discord messages. Introduce a mechanism to 
split messages into 2000 character chunks and add an alternate 
string for cases where the output exceeds this limit. This 
ensures that users receive meaningful feedback without 
truncation, enhancing the overall user experience.

feat: enhance stone status output handling

---

scripts/create_animated_emoji.sh

Introduce a new script that processes PNG files to generate 
GIFs for emojis The script identifies specificnaming patterns in PNG files, extracts relevant 
, and creates GIFs optimized sizes. Thisenhances the emoji creation workflow and ensures 
consistent output formats.

feat: add script to create animated emojis from PNGs

---

src/boost/timer.go

Fixed issue where old timer messages weren't removed

feat(timer): implement mutex for timer management and cleanup

---

src/boost/stones.go

Update stone laying and shipping rates to account for private farms, 
ensuring correct calculations and adding

fix: adjust stone rates for private farms and logging

---

src/events/launch_slashcmd.go

Update launch command string replace "exLnr" with "

refactor: launch command string for clarity

---

src/boost/boost_cooptval.go

This commit introduces the following changes:
1. Detect if a Generous Gift (GG) event is active based on the `gg` and `ugg` values.
2. Calculate the future token value log for both regular and GG tokens.
3. Sort the future token value log in descending order.
4. Append the GG token value log to the regular token value log and sort it in descending order.
5. Modify the `calculateTokenValueCoopLog` function to use the new future token value logs and display the information in a formatted table.
6. Remove the unused `tablewriter` import.
The main focus of this change is to provide more accurate and detailed information about the token value based on the contract duration and the presence of a GG event.

feat: Implement GG token detection and future token value calculation

---

src/boost/boost_cooptval.go

The changes in this commit add a timestamp to the token value log in the `calculateTokenValueCoopLog` function. This allows the user to see when each token value was calculated, which can be useful for understanding the timeline of the token value changes.
The changes include:
- Adding a new variable `futureTokenLogTimes` to store the timestamps for each token value in the `futureTokenLog` array.
- Adding a new variable `futureTokenLogGGTimes` to store the timestamps for each token value in the `futureTokenLogGG` array.
- Updating the `formatStr` variable to include the timestamp for each token value in the log output.
- Sorting the `futureTokenLogTimes` and `futureTokenLogGGTimes` arrays to ensure the timestamps are in chronological order.
These changes improve the readability and …

feat(boost): Add timestamp to token value log

---

src/boost/boost_cooptval.go

The changes in this commit address the following:
- Limit the number of future token log entries to a maximum of 100 to
improve performance and prevent excessive memory usage.
- Ensure that the index for the `valueTime` array is within bounds when
formatting the time string to avoid potential out-of-bounds errors.
- Remove unused `tokenCount` map, as it is not necessary for the
functionality.

feat: Limit future token log entries to 100

---

src/boost/boost_button_reactions.go
src/boost/state_banker.go
src/bottools/tokens.go
src/track/track.go

The changes made in this commit improve the display and logging of token values:
1. Fixed a bug where `futureTokenLogGGTimes` was not being updated correctly.
2. Updated the token logging to include the current time when recording token transactions.
3. Improved the formatting of the token value display in

feat(tokens): Improve token value display and logging

---

src/bottools/tokens.go
src/track/track.go

This commit introduces several improvements to the token tracking functionality:
1. Adds support for dynamic token tracking, which calculates the current rate of token generation based on the actual token usage.
2. Displays the dynamic token generation rate in a new "Future Tokens (Dynamic)" field.
3. Adds a "Future Token Times" field to show the timestamps of the future token values.
4. Optimizes the calculation of future token values and times to reduce redundant computations.
These changes provide users with more accurate and detailed information about their token usage and future token availability, allowing them to better plan and manage their token-based activities.

feat: Implement dynamic token tracking and display

---

src/boost/teamwork.go

This commit improves the formatting of the Teamwork and Delivery information displayed in the Discord message. The changes include:
- Removing the code block formatting for the Teamwork information, as it was making the text harder to read.
- Replacing the use of the `tablewriter` library with custom formatting using `fmt.Fprintf()` to create a more compact and readable table-like display.
- Updating the Delivery information formatting to use the same custom table-like display, making it more consistent with the Teamwork information.
- Removing the unused `olekukonko/tablewriter` import.
These changes aim to enhance the overall readability and presentation of the Teamwork and Delivery information in the Discord message.

feat: Improve Teamwork and Delivery display formatting

---

src/boost/stones_pages.go

The changes optimize the table parsing logic in the `stones_pages.go` file.
Previously, the code used a loop to append each line to a new slice.
The updated code appends the entire table slice directly, which is more
efficient.

feat(stones_pages): Optimize table parsing by appending directly

---

src/boost/stones_pages.go

The changes in this commit focus on optimizing the cache management in the
stones_pages.

feat(stones_pages): Optimize cache management and remove unused code

---

src/boost/stones.go

The changes in this commit center the "Name" column in the table header
to improve the visual alignment of the table data. This makes the table
more readable and aesthetically pleasing.

feat(stones): Center the "Name" column in the table header

---

src/boost/stones.go

Refactor the user name handling logic to use a more efficient
approach. The previous implementation used a loop to iterate
over the runes in the user name and replace any multibyte
characters with a placeholder. This has been replaced with a
commented-out block, as the new approach is more concise and
likely more performant.

feat(stones): Improve user name handling

---

go.mod
go.sum

The changes update the discord go library to the latest version
available. This is done to ensure the application is using the most
up-to-date and secure version of the library, which may include bug
fixes, security patches, and new features.

feat(deps): update discord go library to latest version

---

src/events/launch_slashcmd.go

This commit introduces several improvements to the mission details display:
- Replaces the previous message embed fields with a more compact and visually appealing layout using Discord message components.
- Adds support for displaying chained EX mission information, indicating that they are extended Henliner/Henerprise missions.
- Handles the case where the mission

feat: Enhance mission details display

---

src/boost/stones.go

The changes in this commit include:
1. Adding a new field `elr2` to the `artifactSet` struct, which represents the ELR after considering the effects of collectibles.
2. Calculating the `elr2` value in the `updateArtifactSet` function, which is the ELR multiplied by the farm population and converted to an hourly rate.
3. Implementing a new function `getDeflectorDropPerc` that calculates the unused deflector percentage based on the players' ELR/SR ratio.
4. Updating the output in the `printResults` function to include the unused deflector percentage if it is greater than 0.
These changes aim to improve the accuracy of the calculations and provide more detailed information to the user.

feat(stones): add elr2 field and calculate unused deflector

---

src/bottools/tokens.go

Refactor the token counting algorithm to remove unnecessary
else block, improving code readability and performance.
The changes focus on simplifying the control flow and
removing redundant code, making the function more concise
and efficient.

feat: Optimize token counting algorithm

---

src/track/track_slashcmd.go

Updates the contract ID in the track command to the provided value.
This change ensures the correct contract ID is used for tracking
purposes.

feat(track): Update contract ID in track command

---

src/boost/boost_change.go

This commit adds a new contract with the ID "rn-egg" and the coop ID "ldt" to the system. It also adds three new farmers to the contract with the IDs 831283419891630091, 429413182004658197, and 663786022211026947. The changes were made to allow users to join the new contract and participate in the coop.

feat: add new contract and farmers to the system

---

src/boost/timer.go

This commit adds a new feature to the timer command, allowing users to set a
"sticky" timer that is remembered across command invocations. The changes
include:
- Adding a new `farmerstate` package to manage user-specific settings
- Updating the `/timer` command to check for a stored "timer" setting and use
that as the default duration if present
- Storing the user-provided duration in the "timer" setting when a new timer is
set
- Making the "duration" option optional, as the sticky timer can be used as the
default
The goal of these changes is to provide a more convenient user experience,
allowing users to easily set a recurring timer without having to re-enter the
duration each time.

feat(timer): Add sticky timer functionality

---

src/boost/teamwork.go

This commit introduces several improvements to the teamwork.go file:
1. Adds support for handling Tachyon and Quantum stones in equipped artifacts, which affect the ELR and SR values respectively.
2. Refactors the `determinePostSiabRate` function to consider the farm capacity and maximum farm size when calculating the adjusted contribution rate after swapping an artifact.
3. Updates the calculation of the `contributionRateInSeconds` field for the `DeliveryTimeValue` struct to use the new adjusted contribution rate.
4. Adds the `originalDelivery` field to the `DeliveryTimeValue` struct to store the original delivery values before the artifact swap.
These changes improve the accuracy of the contribution rate and delivery calculations when dealing with equipped artifacts and their associated …

feat(teamwork): Improve artifact handling and contribution rate calculation

---

src/boost/teamwork.go

The changes in this commit optimize the calculation of the time improvement when swapping a SIAB with a 3-slot artifact. The key changes are:
- Simplify the calculation of the new contribution rate by directly subtracting the SIAB rate and adding the new artifact rate.
- Use a new `calculateTimeImprovement` function to calculate the time difference between the original and new contribution rates.
- Improve the logging output to provide more detailed information about the swap, including the percentage increase in contribution rate and the time improvement.
- Refactor the code to make it more readable and maintainable.

feat(teamwork): Optimize SIAB swap calculation and time improvement

---

src/boost/teamwork.go

Removes the `calculateTimeImprovement` function and simplifies the
`determinePostSiabRate` function by directly calculating the time
improvement based on the provided parameters. This change improves the
overall code readability and maintainability.

feat(teamwork): Optimize time improvement calculation

---

src/boost/teamwork.go

The changes in this commit focus on optimizing the display of contract scores in the teamwork module. The key changes are:
- Removed the code that trims the user's name to 12 characters, as this was causing issues with the display of the contract scores.
- Uncommented the code that appends the contract scores to the `contractScoreArr` array, ensuring that the full user name is displayed.
These changes improve the overall user experience by providing a more accurate and readable display of the contract scores.

feat(teamwork): Optimize contract score display

---

src/boost/teamwork.go

The changes add support for displaying extra information when the coop ID starts with a '?'. This includes printing additional details about the production schedule, such as the target egg amount, initial ELR, delta ELR, alpha, elapsed time, and eggs shipped. The changes also ensure that the extra information is only displayed when the `extraInfo` flag is set, and not when the bot is in production mode.

feat: Add support for extra information in coop status

---

src/boost/teamwork.go

This change adds the calculation and display of Chicken Runs and 
Contract Scores for a given user's contribution to an EI contract. The 
key changes are:
- Calculate the maximum number of Chicken Runs based on the contract duration and maximum coop size
- Compute the Contract Scores for various scenarios, including maximum Chicken Runs and Token Value, sink Chicken Runs and Token Value, and minimum Chicken Runs and Token Value
- Display the Chicken Runs and Contract Scores in the Discord message embed
These changes provide the user with more detailed information about their potential contract performance, allowing them to optimize their contribution strategy.

feat: Calculate and display Chicken Runs and Contract Scores

---

src/boost/contract.go

Removes unnecessary code for handling contract roles and simplifies the
logic for updating the contract playstyle. The changes focus on
improving the efficiency and readability of the contract management
functionality.

feat(contract): Optimize contract role handling and playstyle updates

---

src/bottools/banners.go

This change adds a check to see if the overlay image file exists before attempting to load it. If the file does not exist, it downloads the latest egg images from the GitHub repository.
The changes also include:
- Resizing the overlay image to a fixed size of 128x128 pixels using the `draw.NearestNeighbor.Scale` function.
- Adjusting the font size of the text overlay if the text is too wide to fit within the available space.
- Refactoring the `addLabel` function to use the adjusted font face.
- Adding a new `DownloadLatestEggImages` function to download the latest egg images from the GitHub repository.
These changes ensure that the latest egg images are always available and that the text overlay is properly sized to fit within the banner image.

feat(banners): Add automatic download of latest egg images

---

src/events/periodicals.go

Updates the configuration for the periodicals event by removing
the commented-out code that attempted to load custom egg data.
This change simplifies the event setup and removes unused code.

feat(events): update periodicals event configuration

---

src/version/version.go

The application version is bumped from 4.0 to 5.0 to reflect a major
release with significant new features and improvements.

feat(version): Bump application version to 5.0

---

src/boost/teamwork.go

The changes in this commit focus on optimizing the calculation and display of Chicken Runs for a given contract. The key changes are:
- Introduce a new `scoreBase` variable that calculates the base contract score without any Chicken Runs or Token Sharing.
- Calculate the incremental score per Chicken Run based on the base score and the maximum number of Chicken Runs allowed.
- Display a table of Chicken Runs with their corresponding scores, without considering Token Sharing.
- Adjust the calculation of the "TVAL Met" and "Sink" contract scores to use the appropriate Chicken Run and Token Sharing values.
- Ensure the maximum number of Chicken Runs is capped at the minimum of half the contract duration in days or 20.
These changes provide a more accurate and informative display of the …

feat(teamwork): Optimize Chicken Run calculations and display

---

src/boost/siab.go

The changes made in this commit improve the calculation of the SIAB contract score by:
- Replacing the `DownloadCoopStatusTeamwork` function with `DownloadCoopStatusSiab` to fetch the correct data.
- Adding a new field to the `contractScores` struct to track the minimum score.
- Enhancing the contract score table to include the minimum score.
- Implementing a new section to calculate the impact of chicken runs on the contract score, without considering token value.
These changes ensure more accurate and comprehensive contract score calculations, providing users with better insights into their SIAB contract performance.

feat(siab): Improve SIAB contract score calculation

---

src/boost/virtue.go

This change enhances the display of egg virtues by providing more
detailed information. The key changes are:
- Adds the next tier value and the number of eggs pending for the
next tier to the output.
- Formats the delivered eggs value using the `ei.FormatEIValue`
function to display it with no decimal places.
- Introduces a `getNextTierAndIndex` function to find the next tier
for a given value and the index of the tier just passed.
- Defines a `tierValues` slice containing all known tiers in
ascending order, which is used by the `getNextTierAndIndex`
function.
These changes provide users with a clearer understanding of their
progress towards the next egg virtue tier.

feat: Improve egg virtue display

---

src/boost/virtue.go

This change enhances the Eggs of Virtue display in the Egg Inc application. The key improvements are:
- Adds the total Soul Eggs (SE) value and the total Eggs of Virtue (TE) count, along with the future TE count.
- Calculates and displays the current and future Earnings Bonus (EB) based on the total Eggs of Virtue.
- Reformats the Eggs of Virtue section to provide a more concise and informative display.
- Removes the Inventory Score, as it is not a critical piece of information for this feature.

feat(virtue): improve Eggs of Virtue display

---

src/boost/virtue.go

The changes in this commit increase the soul egg bonus by a factor of
100. This is done to provide a more significant boost to the player's
progress in the game.

feat(virtue): Increase soul egg bonus by 100x

---

src/boost/virtue.go
src/ei/research.go

This commit introduces two new functions to the `ei` package:
1. `TimeForLinearGrowth`: Calculates the time required to reach a target population with a constant, absolute growth rate.
2. `TimeToDeliverEggs`: Simulates population growth and egg production to find the time required to deliver a certain number of eggs.
The changes were made to provide more advanced calculations for population growth and egg delivery, which are important for the game mechanics.
The `TimeForLinearGrowth` function handles the case where the population grows at a fixed rate, while the `TimeToDeliverEggs` function models a more complex scenario with logistic growth and variable egg production and shipping rates.
These new functions will be used to improve the accuracy and reliability of the game's calculations, …

feat: Implement linear growth and egg delivery calculations

---

src/boost/virtue.go

This change enhances the habitat status display and adds offline egg tracking
functionality. The key changes are:
- Calculates the habitat percentage and displays it along with the current
population.
- Displays the time remaining for the habitat to fill up online or offline.
- Tracks the number of offline eggs accumulated and includes it in the header
message.
- Handles the case where the habitat is full or nearly full (99.9%) by
displaying a locked status.

feat(hab): Improve habitat status display and offline egg tracking

---

src/ei/ei_api.go

Adds a JSON backup of the user data for debugging purposes, but
only when the bot is running in development mode. This helps
developers troubleshoot issues with the user data without
impacting production users.

feat: Add JSON backup for debugging in dev mode

---

src/boost/replay.go

This commit introduces two key changes to the `/replay-eval` command:
1. Adds a new subcommand "active" that allows users to evaluate the details of their active contracts.
2. Enhances the existing "threshold" subcommand by making the "percent" parameter required and removing the "reset" option.
The changes aim to provide users with more flexibility and clarity when using the `/replay-eval` command. The "active" subcommand enables users to quickly assess the status of their current contracts, while the improved "threshold" subcommand makes it easier to summarize contracts below a specific percentage of the speedrun score.

feat(replay): Add active contract summary and improve threshold command
