go.mod
go.sum
main.go

The `dubcap-time` option allows users to specify the time remaining for
the double capacity event. This information is used to calculate the launch
time of missions in relation to the end of the event. The `hhmmss` library
is added to parse the time format provided by users for the double capacity
event.

feat: add support for `dubcap-time` option in mission command

---

main.go

Added a new variable `dubCapTimeCaution` to track 5 minutes before the double capacity event ends. This ensures better visibility and user experience when nearing the event end time. Updated the logic to display the correct bubble color based on time remaining.

feat: Add new variable dubCapTimeCaution to track 5 minutes before double capacity event ends

---

src/boost/boost.go

Increase the window size to show a single booster to be 10 lines. 
Also, ensure that at least 2 previously boosted numbers are displayed. 
This change improves the visibility of boosted numbers in the boost list.

refactor(boostlist): Update logic to display boosted numbers

---

main.go

The variable integerFTLMinValue was renamed to integerZeroMinValue to better reflect its purpose as the minimum value allowed for certain fields in the codebase. This change improves code readability and maintainability. Additionally, updated the code to use this variable in relevant places.

refactor: Rename variable from integerFTLMinValue to integerZeroMinValue for clarity

---

src/track/track.go

Calculate the token delta when a token is sent in order to keep track of the
difference between tokens sent and received more accurately.

feat: Calculate token delta when token is sent

---

src/track/track.go

Save the token data when a token is sent in order to keep track of token values
and calculate the token delta accurately.

feat: Save token data when token sent

---

main.go
src/boost/boost_admin.go

Refactored the admin contract list and finish handlers to improve code
readability and maintainability. Moved the logic for handling these
interactions to separate functions `HandleAdminContractList` and
`HandleAdminContractFinish` respectively. Also updated the `finishContractByHash`
function to properly handle contract completion and cleanup.

feat(boost): Refactor admin contract list and finish handlers

---

src/boost/boost.go

Removed the unused GetContractList and FinishContractByHash functions to clean up the codebase and improve maintainability.

refactor: Remove unused GetContractList and FinishContractByHash functions

---

src/boost/boost.go
src/track/track.go

Adjust the ContractTokenSent function in track.go to check if 'v' is not nil before comparing its ChannelID with the input parameter. This prevents a potential nil pointer error.

fix: Modify contract token sent tracking to prevent nil pointer error

---

main.go

Fix the variable name casing from userId to userID for better consistency
and readability. Update related references accordingly.

refactor: Fix variable name casing in component handler

---

src/track/track.go

When displaying token tracking information, now users have the option to
react with 1️⃣..🔟 to remove errant tokens that were received at a
specific index.

feat: Add option to remove errant received tokens

---

src/track/track.go

Updated the print function to correctly display instructions for removing
errant received tokens at a specific index in the tracking string.

fix: Corrected typo in print function for tracking string

---

src/track/track.go

Removed the unused variable `td.TokenDelta` from the getTokenTrackingString
function in track/track.go to improve code clarity.

fix: Remove unnecessary variable from getTokenTrackingString function

---

main.go

Convert the string representation of booster position to an integer using strconv.Atoi
to improve code readability and maintainability.

refactor: Convert booster position string to int using strconv.Atoi

---

src/boost/boost_reactions.go
src/track/track.go
src/track/track_handlers.go

- Assign a default duration of 12h if the duration string is invalid
- Add UserID tracking for sent and received tokens
- Include UserID in the display of sent and received tokens
- Enable removal of tokens using reactions for received tokens if not final display
- Track actorUserID in ContractTokenMessage for contract token actions.

feat(track): Improve tracking of token sent and received

---

src/track/track.go

Transitional code was added to ensure that user IDs are displayed correctly
in token tracking details when missing. This change addresses an issue where
some user IDs were missing, resulting in incorrect display of token tracking
information.

fix: Add transitional code to fix missing user ID in token tracking details.

---

src/boost/boost.go
src/boost/boost_help.go
src/boost/boost_speedrun.go
src/boost/boost_wish.go

The setSpeedrunOptions function parameters were simplified by removing unnecessary parameters.
The FindContract calls were updated to pass only the required channelID instead of guildID and channelID in boost_speedrun.go and boost.go files.

refactor: Simplify setSpeedrunOptions parameters and FindContract calls

---

main.go

Changed the format of the success message when ping role is updated to include
the mention of the new role.

refactor: Change message format when ping role is successfully changed

---

src/track/track_handlers.go

Change the function to correctly handle token tracking in ReactionAdd.
Update the tokenTrackingTrack function parameters.
Ensure the received token is removed before tracking.

fix(track): Adjust token tracking in ReactionAdd function

---

go.mod
go.sum

Updated google.golang.org/api to version 0.173.0 and go-openai to version 1.22.0
to incorporate the latest features and improvements.

feat: Update google.golang.org/api to v0.173.0 and go-openai to v1.22.0

---

src/boost/boost.go
src/boost/boost_speedrun.go

Adjust how tokens are subtracted in speedrun reactions to avoid missing self-farmed
tokens. Set contract order as fair in speedrun options to ensure fairness in
contract order.

feat: Ensure fair contract order in speedrun and fix token calculation

---

src/track/track_slashcmd.go

If the channelID is different from the interaction's ChannelID, set the linked
and linkReceived variables to false. This ensures proper functionality in the
boost module.

feat: Update linked and linkReceived variables if channelID is different

---

main.go
src/boost/boost_slashcalctval.go
src/track/track_slashcmd.go

Add a new slash command "calc-contract-tval" for calculating token values of
the current running contract. This command allows users to input the total
duration of the contract and calculates their token value based on reactions.
This functionality helps users track their progress within a contract.

feat: Add slashCalcContractTval command and functionality

---

src/boost/boost_speedrun.go

Modified the message to better indicate that players should react with 💃
after kicks to advance the tango. This clarifies the instructions for
players participating in the boost speedrun.

refactor: Update tango advancement message in boost_speedrun (#298)

---

main.go

Only load contract data if the file exists to avoid unnecessary calls to
downloadEggIncContracts.

refactor: Load contract data only if file exists

---

src/boost/boost.go

Adjust contract state and boost position when a booster leaves. If the contract
is completed, set the state to waiting and decrement the boost position. If the
contract is waiting, set the boost position to the length of the order.
Send the next notification accordingly.

feat: Update contract state and boost position when booster leaves

---

src/boost/boost_slashcmd.go

Renamed the function HandlechangeCommand to HandleChangeCommand for
consistency and clarity when handling the /change command.

refactor: Rename function HandleChangeCommand in boost_slashcmd.go

---

src/boost/boost_slashcalctval.go

If an invalid duration format is used in the calculation command, set the duration
to default to 12 hours and notify the user with a message indicating the default format.

feat: Handle invalid duration input in boost command

---

src/boost/boost.go
src/boost/boost_speedrun.go

Add LegReactionMessageID attribute to SpeedrunData structure to store the
Message ID for the Leg Reaction Message. Update the logic in speedrunReactions
function to set the LegReactionMessageID when the Tango reaction is added to a
message and validate the reaction based on the stored Message ID.

feat(boost): Add LegReactionMessageID to SpeedrunData

---

src/track/track.go

Changed the field name in the tracking embed from "Token Value" to "Value" for
better clarity and consistency.

refactor: Modify token value field name in tracking embed

---

main.go
src/boost/boost_slashcmd.go
src/track/track.go
src/track/track_slashcmd.go

Added a new command /token-remove to remove sent or received tokens from
tracking lists. Also added autocomplete functionality for the command.
Adjusted the token tracking structure accordingly.

feat: Add /token-remove command and autocomplete

---

main.go
src/boost/boost.go
src/boost/boost_speedrun.go

Assume Sink sends same number when pressing money emoji. Fix contract
creator identification logic. Update conditions for reaction handling.

fix: Adjust tokensToSend logic in speedrunReactions

---

src/boost/boost_draw.go

Sink booster will always so total number of tokens wanted, just like all other farmers.

feat: Update signup count display in BoostList

---

main.go
src/tasks/tasks.go

Add a new command to manually check for updated Egg Inc contract data in
Discord. When the command is called, the bot will attempt to download the
latest contracts and notify the user if new data has been loaded or not.

feat: Add manual check for new Egg Inc contract data

---

main.go
src/boost/boost.go
src/boost/boost_admin.go
src/boost/boost_draw.go
src/boost/boost_sink.go

Added two new commands to allow users to volunteer as a token sink for a contract:
- GetSlashVolunteerSink: Volunteer as token sink, with confirmation option
- GetSlashVoluntellSink: Voluntell guest farmer as token sink, with farmer and confirmation options.

feat: Add new commands for volunteering as token sink

---

main.go
src/tasks/tasks.go

- Add Cache-Control header to requests for Egg, Inc contracts
- Update schedule to start downloading contracts at 9:00 AM Pacific Time
- Remove unnecessary duplication of contract download times
- Set application timezone to Los Angeles for consistency

feat: Improve contract download scheduling

---

src/boost/boost.go

Replace Mention with UserID in the name variable for sending tokens to the volunteer sink.

feat(boost): Update sendNextNotification to use UserID instead of Mention

---

src/boost/boost.go

Update the name variable to include the Mention field of the Boosters struct in
order to correctly reference the volunteer sink user when sending tokens.

refactor: Update sendNextNotification function

---

main.go
src/tasks/tasks.go

- Skip data update if read within the last 70 minutes
- Use UTC time for cron job scheduling at 16:xx:xx
- Simplify cron job scheduling in ExecuteCronJob

refactor: Improve time handling for Egg, Inc. contracts

---

go.mod
go.sum
src/boost/boost.go

Add new protobuf fields (MaxCoopSize, LengthInSeconds,
ChickenRunCooldownMinutes) to EggIncContract in boost.go.

feat: Add protobuf fields to EggIncContract

---

main.go
src/boost/boost.go
src/boost/boost_help.go
src/boost/boost_slashcmd.go

- Co-op Size is now optional in boost_help.go and boost_slashcmd.go.
- Co-op Size will be pulled from the Contract data if unset in main.go.
- Added CoopSize, LengthInSeconds fields to Contract struct in boost.go.
- Updated CreateContract to set Co-op Size from Contract data if unset.

feat: Update Co-op Size logic and description

---

src/tasks/tasks.go

Add a new force parameter to the downloadEggIncContracts function to allow forcing the download of Egg Inc contracts data regardless of the time since the last update. This change ensures that new data can be loaded when needed.

feat: Add force parameter to downloadEggIncContracts function

---

src/boost/boost.go
src/boost/boost_speedrun.go

When creating a contract, calculate and set the ChickenRuns based on the
contract length, coop size, and cooldown. Updated handling of ChickenRuns
assignment in contract creation and initialization.

feat: Set ChickenRuns on contract creation based on contract length

---

src/boost/boost_slashcmd.go

If coopSize is 0, check if the contract ID provided is valid. If not found in
the list, respond with a message to select from the dropdown list or provide
coop-size parameter.

feat: Add validation for contract ID in slash command

---

main.go
src/boost/boost_handlers.go
src/boost/boost_slashcmd.go

Added a new function HandleContractDelete to facilitate the deletion of a channel contract. This function allows the contract coordinator to delete a contract, with validation for permissions.

feat: Add functionality to handle contract deletion

---

src/boost/boost.go

Add name, description, egg, target amount, and minutes per token fields to
EggIncContract. Update the LoadContractData function to populate these fields
from the decoded buffer if CoopAllowed is true. The target amount field is
populated with values from the GradeSpecs goals.

feat: Update EggIncContract structure and LoadContractData function

---

src/boost/boost.go

Update the contract choice names to include both the contract name and the
contract ID for better clarity and distinction.

refactor: Update contract choice names to include contract name

---

src/tasks/tasks.go

Added cache control headers to the HTTP requests made in tasks.go to prevent caching of responses and ensure fresh data is always retrieved. This improves data accuracy and reliability.

feat: Add cache control headers to HTTP requests

---

src/boost/boost_draw.go

Increased clarity by updating how the signup count is displayed to include
parentheses for Boost users.

refactor: Update signup count display to include parentheses

---

src/boost/boost_draw.go

Add bold formatting to the post contract sink mention in the BoostList output
to improve visibility and distinguish it from regular text.

feat: Add bold formatting to post contract sink in BoostList output

---

src/boost/boost.go
src/tasks/tasks.go
src/track/track.go

Added a new function `ArchiveTrackerData` in the track package to purge stale
tracker data that is older than 4 days. This function is called in
`ArchiveContracts` in the boost package and executed daily as a cron job.

feat: Add functionality to automatically purge tracker data after 4 days

---

src/boost/boost_slashcmd.go
src/launch/launch_slashcmd.go

Add a sun emoji bubble to the launch message if the launch time falls between
the next Sunday at 3pm UTC and the duration after that time. This is to
indicate a special event taking place during that timeframe.

feat: Add sun emoji bubble to launch message based on event start time

---

src/boost/boost_sink.go

Added condition to check if token sink is already set before allowing users to set it,
and provide feedback if it's already in place.

feat: Prevent setting token sink if it's already set in contract

---

src/boost/boost_reactions.go

Added a nil check before appending booster token to avoid potential null pointer
exceptions. This ensures safe operation and prevents unexpected crashes.

refactor: Add nil check before appending booster token

---

src/tasks/tasks.go

- Combine time zone and offset in a single log statement for clarity
- Remove unnecessary individual log statements in the function

refactor: Improve logging in ExecuteCronJob function

---

src/boost/boost_change.go

Changing error message capitalization to capitalize the first letter of the
error string for consistency.

refactor: Update error message capitalization

---

src/boost/boost_draw.go

Simplified the boost list output in the DrawBoostList function by removing
redundant information and keeping only the necessary details like user
mentions and tokens wanted. This change improves the readability of the
output without losing important information.

feat: Simplify boost list output

---

main.go
src/track/track_handlers.go
src/track/track_slashcmd.go

This commit adds the HandleTrackerEdit function to handle editing tracker
details such as contract duration and start time. It parses and updates the
tracker details based on user input. The function also updates the message and
components accordingly.

feat: Add HandleTrackerEdit function for editing tracker details

---

go.mod
go.sum

Updating the google.golang.org/api dependency to version v0.180.0 for compatibility and functionality improvements.

fix: Update google.golang.org/api to v0.180.0

---

src/boost/boost_change.go

Removed the check for contract state in the ChangePingRole function as it is
no longer relevant to the functionality.

fix: Remove check for contract state in ChangePingRole function

---

main.go
src/boost/boost.go
src/boost/boost_change.go

Add a new /change-ping-role command to adjust aspects of a running contract.
This command allows users to change the ping role for the contract.

feat: Add /change-ping-role command

---

src/boost/boost_draw.go

Adds functionality to display a sink icon next to boosted boosters in both
early and late draw lists. This sink icon is shown only for boosters involved
in a speedrun with a specific wonky style and the same sink user ID.

feat: Display sink icon for boosted boosters in draw lists

---

src/boost/boost.go

Renamed the variable boostReactionIcon to boostIconReaction for clarity in the
codebase. This change ensures consistency and improves readability.

refactor: Rename boostReactionIcon to boostIconReaction

---

src/launch/launch_slashcmd.go

Update launch instructions message to clarify that the launch should occur
before the Sunday event starts rather than after it begins.

fix: Update launch instructions message

---

src/launch/launch_slashcmd.go

Storing launch history if "chain" option is provided, else retrieve launch
history for the user.

feat: Add functionality to store launch history if option is provided

---

main.go
src/boost/boost_change.go
src/boost/boost_draw.go

Add a new slash command to change the planned start time of a contract. 
The command allows the contract creator to set or clear the planned start time 
within the next 7 days using Discord timestamps.

feat: Add /change-planned-start command

---

main.go
src/boost/boost.go
src/boost/boost_change.go
src/boost/boost_draw.go
src/boost/boost_reactions.go
src/boost/boost_slashcalctval.go
src/boost/boost_speedrun.go
src/track/track.go

Updated the username in token tracking to show the actual username instead
of the user ID. Added functionality to add multiple reactions to contract
messages based on contract state.

feat: Update username in token tracking and add reactions to contracts

---

src/boost/boost_reactions.go
src/boost/boost_speedrun.go

Added a more efficient way to find the most recent boost time among users and their alts by iterating through the contract order and checking for boosted and idle users.

refactor: Improve logic for finding the most recent boost time among user and alts

---

src/boost/boost_slashcalctval.go
src/farmerstate/farmerstate.go

Added a new sticky setting to show individual token values by default in
the details option. Also, updated the farmerstate package to handle the 
new setting.

feat: Add sticky setting for showing individual token values

---

src/launch/launch_slashcmd.go

Add the formatted duration of the EX Hen to the chainString in the HandleLaunchHelper
function to improve readability and provide additional information to users.

feat: Add formatted duration to chainString in HandleLaunchHelper

---

src/launch/launch_slashcmd.go

Update the chainString variable prefix to +exLnr from +exHen in HandleLaunchHelper function for consistency and clarity.

feat: Update chainString variable prefix to +exLnr

---

main.go
src/boost/boost.go
src/tasks/tasks.go
src/track/track.go

Add parameter to ArchiveContracts function in boost.go and tasks.go to include
a Discord session for handling Discord messages related to token tracking
and contract archiving. Update related functions in track.go to ensure correct
functionality with Discord session.

feat: Add parameter to ArchiveContracts to handle Discord session

---

src/launch/launch_slashcmd.go

Refactor the condition to check if launch time is after the end time of the
fast duration instead of arrival time. This ensures correct calculation of
minutes for the mission duration.

feat: Fix condition comparison for launch time in HandleLaunchHelper

---

main.go
src/boost/boost.go
src/boost/boost_admin.go
src/tasks/tasks.go

- Refactored admin command authorization logic to check user ID in AdminUsers instead of adminUsers
- Renamed admin-related settings to have 'admin-' prefix for clarity and consistency
- Removed slashAdminBotSettings application command due to redundancy

refactor: Update admin command authorization logic and settings naming

---

src/boost/boost_ei_api.go

Added a new function `downloadCoopStatus` to download coop status from
Auxbrain website using HTTP POST request. The function decodes the
response and logs contributor names with equipped artifacts.

feat(boost): Add function to download coop status from Auxbrain

---

main.go
src/boost/boost_admin.go
src/boost/boost_teamwork.go
src/config/config.go

This commit updates the AdminUsers variable to be populated from the config file
instead of being hardcoded in the boost_admin.go file. AdminUsers is now an
empty slice in boost_admin.go and is assigned the value from config.AdminUsers
in main.go and boost_teamwork.go.

refactor: Update AdminUsers variable to be populated from config file

---

src/boost/boost_estimate.go

Changed the boost coefficient in the contract duration estimate calculation
to better reflect the game dynamics.

refactor: Update contract duration estimate calculation boost coefficient

---

src/boost/boost_slashcmd.go

Add functionality to append the New York time to the thread name when a
sign-up contract has a planned start time in the America/New_York timezone.
Also, update message to prompt users to use `/change-planned-start` for
contracts without an immediate start.

feat: Add New York time to thread name on sign-up contract start

---

src/boost/boost_button_reactions.go
src/boost/boost_draw.go
src/boost/boost_speedrun.go

Add logic to clear reactions for users with alts and allow them to select again if needed.
Improve message for waiting on CRT chicken runs to include total count.

feat: Improve button reaction handling for chicken runs

---

main.go
src/boost/boost.go
src/boost/boost_speedrun.go

Added a slash command to change speedrun sink assignments of a running contract.
Included options for different sink scenarios like CRT, boosting, and post-contract.

feat: Add slash command to change speedrun sink assignments

---

src/boost/boost.go
src/boost/boost_speedrun.go

If the number of legs in a speedrun contract is 0, remove the Self Runs
style flag. Otherwise, add the Self Runs style flag.
Flag isn't used yet but adding it for future use

feat: Update contract style based on legs in speedrun

---

src/boost/boost.go
src/boost/boost_draw.go

Removed deprecated contract token handling code that was set to be removed after June 30th.
Updated contract flags to use proper hexadecimal values for clarity and consistency.

refactor: Remove deprecated contract token handling and update contract flags訂

---

main.go
src/boost/boost.go
src/boost/boost_slashcmd.go
src/boost/thread.go

Add a new slash command to rename the contract thread using user inputs and
provide customization options for the thread name.

✨ feat(boost): Add functionality to rename contract thread

---

src/boost/boost_handlers.go
src/boost/contract.go

Allow users to differentiate between contracts in a channel and contracts in a thread.

✨ Add thread option in contract settings

---

src/boost/artifacts.go
src/ei/ei_data.go

Add conditional logic to retrieve the `CARBON-FIBER` and `PUMPKIN` emojis from the Egg Inc. Discord and update their corresponding IDs in the `getArtifactsComponents` function.

feat: Update artifact components emojis

---

src/boost/boost_handlers.go

Changed "Boost order is based on ELR" to "Highest ELR first" in description.

feat(boost): Update Boost order description

---

src/boost/boost_calctval.go
src/boost/contract.go

feat: Add initial response message for contract calculation request
refactor: Limit displayed user names to 12 characters in booster calculation data
fix: Use FollowupMessageCreate instead of InteractionRespond for follow-up message

refactor: Update contract creator IDs and limit displayed user names to 12 characters

---

main.go
src/farmerstate/farmerstate.go
src/farmerstate/privacy.go

Keep only the last 10 order percentiles in FarmerState for each user. Add a new
data privacy setting and update data modification functions to respect this
setting.

feat: Implement privacy setting for user data

---

main.go

This pull request addresses the issue where the handle method for Stones auto-complete was incorrectly using Contract instead of Stones. The fix ensures that the correct handling method is now being utilized, resolving the issue at hand.
- Switched handle method for Stones auto-complete from Contract to Stones
- fix: Switched handle method for Stones auto-complete from Contract to Stones.

fix: Switched handle method for Stones auto-complete from Contract to Stones.

---

src/boost/boost_teamwork.go

Update the timestamp format from 'R' to 't' for better readability in 
the teamwork messages. This change improves the user experience by 
ensuring the timestamps are displayed in a more user-friendly manner, 
making it easier for users to understand the timing of events 
related to the SIAB.

fix: update timestamp format in teamwork messages

---

src/track/track.go

Eliminate commented-out variables in the resetTokenTracking function. This 
cleans up the code and improves readability by removing unnecessary 
clutter, focusing on the essential components of the function.

refactor: remove unused token tracking variables

---

go.mod
go.sum

Updates the google.golang.org/api dependency to version v0.204.0 
to incorporate the latest bug fixes and improvements. This change 
ensures better compatibility and performance with the current 
project dependencies.

chore(deps): update google.golang.org/api to v0.204.0

---

src/tasks/tasks.go

Update the function signature and all references to the 
`finalname` variable to `filename` for consistency. This 
change improves code readability and maintains uniformity 
across the function. Additionally, adjust the `Expires` 
header to set a more appropriate value based on the 
current time.

fix: correct variable name from finalname to filename

---

go.mod
go.sum

Update the googleapis genproto dependencies in go.mod and go.sum to 
the latest versions. This change ensures compatibility with recent 
updates and improvements in the Google APIs, enhancing overall 
functionality and stability of the application.

chore: update googleapis genproto dependencies

---

src/boost/boost.go
src/boost/boost_draw.go
src/boost/boost_handlers.go
src/boost/contract.go

Introduce new token boost options for contracts, allowing users to select 
between 6 and 8 token boosts. Update the contract style flags to include 
`ContractFlag6Tokens` and `ContractFlag8Tokens`. Modify the contract 
handling logic to set the desired tokens based on user selection, and 
update the output display to reflect the selected boost type. This 
enhances user experience by providing more flexibility in boost options.

feat: add support for 6 and 8 token boosts

---

src/boost/boost.go
src/boost/boost_draw.go

Update the token count logic in AddContractMember and 
AddFarmerToContract functions to set desired tokens based 
on contract style when the contract state is not in 
signup. Remove unused error

feat: adjust token count based on contract style

---

src/boost/boost_handlers.go

Update the descriptions for the 6 and8 token boost options in the 
signup contract settings. Change the wording to clarify that users 
join with the intention of obtaining these boosts, enhancing the 
user experience and understanding

fix: update descriptions for token boost options

---

src/boost/boost.go
src/boost/boost_reactions.go

Add checks to ensure tokens are only set when the contract does not 
control the wanted tokens. This prevents unintended token adjustments 
when specific contract styles are active, improving the integrity of 
token management in the system.

feat(boost): conditionally set tokens based on contract style

---

src/boost/artifacts.go
src/ei/ei_data.go

Add Lithium artifact with 10% vehicle cost to the ArtifactMap. 
Increase the maximum selectable values for colleggtibles from 6 to 7. 
Include Lithium in the artifacts options with its corresponding emoji 
and description. Update the EggEmojiMap to include Lithium's emoji 
data for consistency across the application.

feat: add Lithium artifact and update related components

---

src/boost/artifacts.go

Change the default value for the Lithium artifact in the 
getArtifactsComponents function to correctly reflect its 
association with the "Lithium" string instead of "Pumpkin". 
This ensures accurate behavior in the application logic.

fix: update default value for Lithium artifact

---

src/boost/artifacts.go

Update description for the Lithium component to a 
consistent format by changing "10% Vehicle Cost" to 
"-10% Vehicle Cost". This improves clarity and aligns with 
the formatting of other components.

fix: correct Lithium description in artifacts

---

src/boost/stones.go

Remove outdated logic for deflector percent calculation and replace it 
with a more efficient method that checks the BuffHistory for the best 
deflector percentage. This change improves clarity and ensures that 
the most relevant deflector data is used when none is initially 
available.

refactor: update deflector handling in DownloadCoopStatusStones

---

src/boost/stones.go

Change the deflector abbreviation from a static value to a dynamic 
percentage format. This improves clarity by providing the actual 
deflector percentage instead of a generic label, enhancing the 
information conveyed in the notes.

fix: update deflector abbreviation format in stones.go

---

src/boost/state_banker.go

CRT Sink may have tokens and be ready to boost, this allows them to activate the Bag icon while in boost phase

CRT Sink can trigger sink boost

---

src/boost/boost_cooptval.go

This change adds support for tracking the time values associated with the
future token log values. Previously, only the log values were tracked,
but now the corresponding time values are also stored and used when
calculating the token value.
This allows for more accurate representation of the token value over time,
as the time information is now available in addition to the log values.

feat(boost): Add support for future token log times

---

src/boost/boost_button_reactions.go
src/boost/boost_calctval.go
src/boost/boost_cooptval.go
src/boost/boost_draw.go
src/boost/boost_slashcmd.go
src/boost/state_banker.go
src/bottools/tokens.go
src/track/track.go

The changes in this commit introduce a new package `bottools` that provides utility functions for calculating token values and future token logs. The main changes are:
1. Added the `GetTokenValue` function to calculate the token value based on the given time and duration parameters.
2. Added the `CalculateFutureTokenLogs` function to calculate the future token logs based on the given parameters, including the start time, duration, and token generation rate.
3. Added the `CalculateTcountTtime` function to calculate the token count and time based on the given token value and value log.
These utilities are used in the `track` and `boost` packages to handle token-related calculations and operations.

feat(bottools): add token value calculation utilities

---

src/track/track.go

Calculates the dynamic tokens per second rate based on the current sent count and
time since start. This provides a more accurate estimate of the future token
logs, especially when the token rate is changing over time.

feat: Improve token tracking dynamic calculation

---

src/track/track.go

The changes update the logic for displaying the duration of a token
tracking event. Previously, the duration was calculated based on the
difference between the start time and the time from the coop status.
This has been changed to use the pre-calculated duration time, which
provides a more accurate and consistent display of the duration.

feat(track): update duration display logic

---

src/boost/boost.go
src/boost/boost_cooptval.go
src/bottools/tokens.go
src/track/track.go

This change adds two new fields to the `Contract` struct: `TimeCRT` and `TimeBoosting`. These fields store the timestamps when the contract was created and when the boosting started, respectively.
The changes also update the `changeContractState` function to set these timestamps when the contract state changes to `ContractStateCRT` and `ContractStateBanker`.
Additionally, the `CalculateFutureTokenLogs` function in `bottools/tokens.go` has been updated to accept a `crtTime` parameter, which is used to offset the token generation times based on the contract creation timestamp.

feat: Add contract creation and boosting timestamps

---

src/boost/boost.go
src/boost/boost_cooptval.go
src/bottools/tokens.go
src/track/track.go

The changes in this commit improve the calculation of future token logs by:
1. Introducing a `FutureToken` struct to represent a token with its value and time.
2. Simplifying the return values of `CalculateFutureTokenLogs` to only return the future token logs, without separate time arrays.
3. Extending the end time of the token log calculation to 2 hours beyond the contract end time to provide more accurate estimates.
4. Updating the `calculateTokenValueCoopLog` and `getTokenTrackingEmbed` functions to use the new `FutureToken` struct.
These changes make the code more concise and easier to work with, while also improving the accuracy of the future token log calculations.

feat(bottools): Improve future token log calculation

---

src/boost/stones.go
src/boost/teamwork.go

This commit focuses on improving the formatting and readability of the coop status output in the `stones.go` and `teamwork.go` files.
The key changes are:
- Removed unnecessary commented-out code in `stones.go` that was configuring the table writer.
- Wrapped the "Deliveries" and "Teamwork" values in code blocks (`````) in `teamwork.go` to make them more readable.
- Improve

feat: Improve formatting and readability of coop status output

---

src/boost/boost_button_reactions.go

This change ensures that the user ID provided is actually part of the
contract before processing the boost state. This prevents potential
issues where a user not in the contract could attempt to interact with
the boost functionality.

feat: Ensure user is in contract before processing boost

---

src/boost/state_banker.go

Adds logic to manage the boost position when a user boosts the sink.
This ensures that the boost state and start times are updated correctly
when a user boosts the sink.

feat(boost): Implement boost position management

---

src/boost/boost_slashcmd.go

Handles the error returned from RedrawBoostList by ignoring it.
This ensures that the function can continue to execute even if
there is an issue with redrawing the boost list.

feat(boost): handle error from RedrawBoostList

---

src/boost/teamwork.go
src/ei/coop_status.go

This commit includes two main changes:
1. Reduce the expiration time for EI data from 1 minute to 30 seconds. This helps to keep the cache more up-to-date and responsive to changes in the cooperative status.
2. Improve the calculation of buff time values by using the estimated end of the contract as the reference point, rather than the server timestamp. This ensures that the buff time values are displayed correctly, even when the contract has been running for some time.

feat: Optimize EI data expiration and improve buff time calculation

---

src/boost/teamwork.go

Adjust the calculation of the contract duration to correctly handle cases
where the contract has been completed. This ensures that the contract
duration is accurately reflected in the UI, even when the contract has
been completed.

feat(teamwork): Adjust contract duration calculation

---

src/boost/teamwork.go

The changes made in this commit ensure that the "Offline" and "Future" delivery time values are only added to the `DeliveryTimeValues` slice if `calcSecondsRemaining` is greater than 0. This prevents the creation of unnecessary delivery time values when the user has no remaining time on their farm.

feat(teamwork): Add conditional check for calcSecondsRemaining

---

src/boost/stones.go
src/boost/teamwork.go
src/bottools/utils.go

The changes in this commit focus on optimizing the calculation of contract duration and buff time value in the `stones.go` file. The key changes are:
1. Correctly calculate the `calcSecondsRemaining` value by using the `GetSecondsSinceAllGoalsAchieved()` method from the `coopStatus` object.
2. Update the calculation of `BuffTimeValueCRT` to use the correct `equipTimestamp` value, which is the original server timestamp plus the `calcSecondsRemaining`.
These changes ensure that the contract duration and buff time value are calculated accurately, which is crucial for the correct display of teamwork information.
Additionally, the changes in `teamwork.go` improve the formatting and alignment of the teamwork output, making it more readable and visually appealing.

feat: Optimize contract duration calculation and buff time value

---

src/boost/stones_pages.go

Updates the stones cache and triggers an update to the estimated
time for the channel. This ensures the estimated time is kept
up-to-date as the cache is updated.

feat(stones_pages): Update cache and estimate time

---

src/boost/boost.go
src/boost/stones.go
src/boost/stones_pages.go
src/boost/teamwork.go

This change updates the contract start time and estimated duration in the contract
object when the contract status is updated. This ensures that the contract
information displayed in the boost list message is accurate and up-to-date.
The key changes are:
- Added a new `UpdateContractTime` function to update the contract start time and
estimated duration
- Updated the `teamwork.go` and `stones.go` files to call the `UpdateContractTime`
function when the contract status is updated
- Added a check to only refresh the boost list message if the `EstimateUpdateTime`
is within 10 seconds of the current time, to avoid unnecessary updates

feat: update contract start time and duration

---

src/boost/stones.go
src/boost/stones_pages.go

The changes made in this commit optimize the boost list refresh logic by
only refreshing the list if the contract is in the completed state and the
EstimateUpdateTime is within 10 seconds of the current time. This helps
to reduce unnecessary API calls and improve the overall performance of
the application.

feat(boost): Optimize boost list refresh logic

---

src/boost/boost.go

The changes made in this commit update the `UpdateContractTime` function to
only update the contract start time and estimated duration if the contract
is in the `ContractStateCompleted` state. This ensures that the function
does not attempt to update contracts that are not in the completed state,
which could lead to unexpected behavior.

feat(contracts): Update contract time only for completed contracts

---

src/events/launch_slashcmd.go

Modify the event message formatting in the `launch_slashcmd.go` file to
enhance the readability and consistency of the displayed information.
Specifically, remove the extra space between the event icon and the event
message, ensuring a more compact and visually appealing presentation.

feat: Improve event message formatting

---

src/boost/teamwork.go

Modify the calculation of `futureDeliveries` to ensure that the
contribution rate is never negative, even when the remaining time is
less than zero. This prevents the contribution amount from being
incorrectly reduced when the coop has already achieved its goals.

feat(teamwork): Ensure contribution rate is non-negative

---

src/boost/estimate_scores.go

The changes made in this commit add a new option to the estimate scores command in the Discord bot. The "private-reply" option allows the user to choose whether the response should be visible to everyone in the channel or only to the user who triggered the command.
The default behavior is now to make the response public, and the user can opt-in to a private (ephemeral) reply by setting the "private-reply" option to true.
Additionally, the commit updates the logic to handle the "private-reply" option an

feat(discord): Add private reply option to estimate scores command

---

go.mod
go.sum

The changes in this commit upgrade the discordgo dependency from
version v0.28.2-0.20250522172923-b17704c79361 to v0.29.0. This update
is necessary to take advantage of the latest features and bug fixes
available in the discordgo library.

feat(go.mod): Upgrade discordgo dependency to v0.29.0

---

src/boost/boost_import.go
src/boost/estimate_time.go
src/ei/ei_data.go
src/ei/ei_units.go

The changes remove the unused `TargetAmountq` field from the `ContractGrade` and `Contract` structs. This field was previously used to store the target amount in quintillions, but it is no longer needed as the `TargetAmount` field already stores the target amount in the correct format.
The changes also update the `getContractDurationEstimate` function to use the `TargetAmount` field instead of the `TargetAmountq` field, and the `FormatEIValue` function to handle the formatting of the target amount.

feat(boost): remove unused TargetAmountq field

---

src/boost/estimate_scores.go
src/boost/teamwork.go

The changes made in this commit are:
1. Reordered the score columns in the scores table to display the "TVAL" column before the "SINK" column.
2. Updated the footer in the `estimate_scores.go` and `teamwork.go` files to reflect the new order of the score columns.
The motivation behind these changes is to improve the readability and consistency of the scores table by aligning the order of the score columns with the order presented in the footer.

feat(scores): Reorder score columns and update footer

---

src/boost/boost_draw.go
src/bottools/tokens.go

The changes in this commit improve the token value calculation logic in the `tokens.go` file. The main changes are:
- Rename the `uTval` variable to `userTokenValue` for better readability.
- Simplify the logic for calculating the token count and time by removing the unnecessary `else` block.
Additionally, the changes in `boost_draw.go` file:
- Add a new `targetTval` variable to store the target token value.
- Adjust the `targetTval` value based on the estimated duration of the contract, with a minimum value of 0.07 * BTA (Boost Time Allocation).
- Update the `currentTval` variable to use the new `GetTokenValue` function.
These changes aim to improve the accuracy and flexibility of the token value calculation, which is crucial for the overall functionality of the bot.

feat(tokens): Improve token value calculation logic

---

src/boost/boost_draw.go
src/boost/estimate_scores.go

The changes in this commit improve the display of the current TVal in the boost draw
function. The previous implementation only showed the current TVal, but now it also
displays the target TVal for comparison. This provides more useful information to the
user about the progress of the boost.

feat(boost): Display target and current TVal in boost draw

---

src/boost/stones.go

Modify the deflector display and calculation logic to provide more
accurate and visually appealing results. Specifically:
- Round the deflector percentage to the nearest whole number when
displaying it in the `abbrev` field.
- Use the `math.Ceil()` function to round up the deflector percentage
when appending the note.
These changes ensure that the deflector percentage is displayed in a
more user-friendly manner, while maintaining the accuracy of the
underlying calculation.

feat: Improve deflector display and calculation

---

src/boost/stones.go

The changes in this commit improve the calculation and display of the egg
laying rate (ELR) deflector percentage. Specifically:
- The `buffElr` value is now rounded to the nearest integer using `math.Round()`
instead of being truncated.
- The `as.note` and `as.deflector.abbrev` fields are now using the rounded
`bestDeflectorPercent` value instead of `math.Ceil()`.
These changes ensure that the displayed deflector percentage is more accurate
and visually appealing.

feat: Improve egg laying rate calculation and display

---

src/boost/boost_slashcmd.go
src/boost/boost_track.go

The changes made in this commit improve the autocomplete functionality for the "new-receiver" option in the boost command. The key changes are:
1. Change the type of the "new-receiver" option from `discordgo.ApplicationCommandOptionInteger` to `discordgo.ApplicationCommandOptionString` to allow for more flexible input.
2. Implement a sorted list of booster nicknames as the autocomplete choices, with the ability to filter the list based on the user's input.
3. Update the logic in the command handler to use the new string-based "new-receiver" option instead of the previous integer-based approach.
These changes enhance the user experience by providing a more intuitive and responsive autocomplete feature for selecting the new receiver of a token.

feat(boost): Improve autocomplete for new-receiver option

---

src/bottools/banners.go
src/events/periodicals.go

The changes in this commit add a permissions check for the ACO channel before sending a message. This ensures that the bot has the necessary permissions to send messages in the channel, and logs a warning if it does not. This is an important change to prevent errors and ensure the bot's functionality.

feat(periodicals): Add permissions check for ACO channel

---

src/boost/boost_button_reactions.go
src/boost/boost_cooptval.go
src/boost/boost_draw.go
src/bottools/tokens.go
src/ei/ei_data.go
src/events/periodicals.go
src/track/track.go

The changes in this commit improve the handling of the generous gift event in the `boost_button_reactions.go` file. Specifically, the `GetGenerousGiftEvent()` function is now called with an additional return value, which is used to determine the end time of the generous gift event. This ensures that the future token log only includes tokens that are generated before the end of the generous gift event.
feat(tokens): Optimize future token log generation
The changes in this commit optimize the generation of the future token log in the `tokens.go` file. The `endGG` variable is now used to filter the future token log, ensuring that only tokens generated before the end of the generous gift event are included. This helps to improve the accuracy and performance of the token value calculations.

feat(boost_button_reactions): Improve handling of generous gift event

---

src/boost/boost_button_reactions.go

Refactor the `getContractReactionsComponents` function to handle the case
where `contract.buttonComponents` is `nil`. This ensures that the function
does not panic when trying to access a component that is not present in the
map. Additionally, add a warning log message when a component is missing
for a given contract.

feat(boost): Improve contract reactions components handling

---

src/boost/boost_button_reactions.go
src/boost/boost_draw.go
src/boost/state_banker.go
src/ei/ei_data.go

Adds a text outline effect to the banner text by rendering the text at multiple offset positions with a black outline color. This creates a more visually appealing and readable text on the banner.
feat(state_banker): Update boost contract state when boosting
Updates the boost contract state when a user is boosting, including setting the end time and duration of the boost, and updating the boost position in the contract.
feat(boost_button_reactions): Add boost flag to token log entries
Adds a `Boost` flag to the token log entries to indicate whether the tokens were sent as part of a boost or not. This provides more context and information about the token transactions.

feat(banners): Add text outline effect to banner text

---

src/boost/boost_menu.go
src/boost/state_crt.go

Adds the calculation of tokens received and sent for the current
banker in the state_crt.go file. This ensures that the tokens
received value is accurate, taking into account any boosting
that has occurred.
feat(boost): add boost indicator to token logs
Adds a boost indicator (🚀) to the token logs in the boost_menu.go
file, to visually indicate when a boost has occurred. This provides
more context to the user when viewing the token transaction history.

feat(boost): add tokens received and sent calculation

---

src/boost/boost_button_reactions.go

Adds a new select menu option to send a token to the next booster in the
contract's boost order, but only if the current booster has not yet
received all the tokens they requested.

feat(boost): Add token send option for next booster

---

src/boost/boost.go
src/boost/boost_button_reactions.go
src/boost/boost_menu.go

The changes in this commit add a new `TokenRequestFlag` field to the `Booster` struct in the `boost` package. This flag is used to indicate whether a booster has requested a token or not.
Additionally, the `boost_menu.go` file has been updated to include a new "Token Farmer" link in the boost tools section, and the `boost_button_reactions.go` file has been updated to handle the new token request functionality.
The key changes are:
1. Added a new `TokenRequestFlag` field to the `Booster` struct in `boost.go`.
2. Updated the `boost_menu.go` file to include a new "Token Farmer" link in the boost tools section.
3. Updated the `boost_button_reactions.go` file to handle the new token request functionality, including adding a new select menu option to request a token and a new case to handle the …

feat(boost): add token request flag and token request UI

---

src/boost/boost_menu.go

This commit introduces two major changes to the boost contract system:
1. Adds a new "Token Ask" order option, where boosters who ask for fewer tokens will boost earlier.
2. Adds new playstyle options, including "Chill", "ACO Cooperative", "Fastrun", and "Leaderboard", which allow players to customize the contract experience.
The changes were made to provide more flexibility and customization options for contract participants, allowing them to choose the boost order and playstyle that best suits their preferences and strategies.

feat(boost): Add token ask order and playstyle options

---

src/events/launch_slashcmd.go

The changes in this commit introduce new playstyle options for contracts and a new boost order option based on token ask amount.
The new playstyle options include:
- Chill: Everyone fills habs and uses correct artifacts
- ACO Cooperative: Chill + Everyone checks in on time
- Fastrun: ACO + Get TVal and CR from your coop size or act as sink
- Leaderboard: Fastrun + Get max CR
The new boost order option "Token Ask Order" sorts boosts based on the amount of tokens asked for, with those asking for less tokens boosting earlier.
These changes provide more flexibility and customization options for contract participants, allowing them to choose the playstyle that best suits their preferences and goals.

feat(boost): add new playstyle options and token ask order

---

src/boost/contract.go
src/boost/state_banker.go

The changes in this commit add the boost trigger time to the contract. This is
necessary to properly track the duration of the boost and ensure that the
boost is applied correctly. The changes also include a check to see if the
play style has changed, and if so, update the thread name accordingly.

feat(boost): add boost trigger time to contract

---

src/events/launch_slashcmd.go

The changes made in this commit improve the display of the response to the
launch slash command. Specifically:
- The events text is only included in the response if there are any events to
display.
- The error handling for sending the followup message has been improved to
print any errors that occur.
These changes ensure a cleaner and more informative response to the launch
command, and provide better error handling for the command execution.

feat(events): improve display of launch command response

---

src/boost/contract.go

Refactor the coop ID parsing logic to better detect the "chill" playstyle.
Previously, the code only checked for "chill" at the start or end of the
string, which was too narrow. Now, it also checks for "chill" anywhere in
the string, including in the middle (e.g., "my-chill-coop").

feat(contract): Improve coop ID parsing for chill playstyle

---

src/boost/boost_button_reactions.go
src/boost/boost_reactions.go
src/boost/thread.go

The changes made in this commit improve the help message displayed to users when they interact with the "help" button in the Boost Bot. The main changes are:
1. The help message now includes a link to the relevant contract playstyle information, if the contract has a playstyle set. This allows users to easily access more details about the different playstyles supported by the bot.
2. The formatting of the help message has been improved by using a `strings.Builder` to construct the output string, which makes the code more readable and maintainable.
3. The cooldown time for updating the contract duration has been reduced from 3 minutes to 10 seconds, as this is a common operation that users may need to perform frequently.
chore: Reduce duration update cooldown to 10 seconds
The changes in …

feat: Improve help message with contract playstyle links

---

src/boost/boost_menu.go

The changes fix a typo in the name of the Tokification Android app. The
name is corrected from "TTokification" to "Tokification" to match the
actual app name.

feat: Fix typo in Tokification app name

---

src/boost/boost_draw.go

Adds a new token value display and a separator to the guidance message
when the contract is in the waiting state. This provides more
informative guidance to users about the current token value and
encourages them to join the boost by reacting with the 🧑‍🌾 emoji.

feat(boost): Add token value display and separator in waiting state

---

src/boost/contract.go

Adds a new condition to override the contract style based on the play
style. This is only applied for the leaderboard play style, where the
contract style is set to ContractFlagBanker | ContractFlagCrt.
Additionally, the SRData.StatusStr is updated to reflect the new
contract style.

feat(contract): Enhance contract style for leaderboard play style

---

src/boost/help.go
src/bottools/app_cmdlinks.go

The changes in this commit add support for two new subcommands to the "change-planned-start" command: "change-start offset" and "change-start timestamp". This allows users to set the planned start time for a contract using either a time offset or a specific timestamp.
The commit also updates the help message to reflect these new subcommands, making it clearer for users how to set the planned start time for a contract.

feat(help): Add new subcommands for changing contract start time

---

src/boost/boost_handlers.go

This commit adds two new commands to the boost bot:
1. `change-start offset`: Allows users to set a planned start time for the
contract by specifying an offset from the current time (e.g. "+2h").
2. `change-start timestamp`: Allows users to set a planned start time for the
contract by specifying a timestamp (e.g. "2023-04-01 12:00:00").
These commands are added to the sign-up message to provide users with more
flexibility in scheduling their contracts.

feat(boost): Add commands to change planned start time

---

src/boost/contract.go

Adds thread style icons to the contract IDs in the contract creation
process. This provides a visual cue for the player to quickly identify
the contract type (e.g. Enlightenment, Tachyon, etc.) when viewing the
contract list.

feat(contract): Add thread style icons to contract IDs

---

src/boost/boost_handlers.go
src/boost/contract.go

The changes in this commit update the logic for determining the contract playstyle based on the contract's style flags. The main changes are:
- If the contract has the CRT flag set, the playstyle is set to Leaderboard, regardless of the previous playstyle.
- If the contract does not have the CRT flag set and the previous playstyle was Leaderboard, the playstyle is set to Fastrun.
- The `Speedrun` field is replaced with a more generic `Style` field that uses bit flags to represent the contract's characteristics.
These changes ensure that the contract playstyle is correctly determined based on the contract's style, simplifying the logic and making it more flexible for future contract types.

feat(boost): change contract playstyle logic

---

src/boost/timer.go

The changes made in this commit include:
1. Removing the unused `duration` variable assignment of `1 minute`.
2. Adjusting the default timer duration to `3 minutes and 30 seconds`.
3. Removing the unnecessary `duration` variable assignment and using the existing `duration` variable instead.
These changes improve the code by removing unused code and adjusting the default timer duration to a more appropriate value.

feat(timer): Adjust default timer duration and remove unused code

---

src/boost/boost.go

The "ACO Cooperative" playtstyle name is changed to "ACO Coop" to
make it more concise and easier to read. This change is part of a
larger effort to improve the readability and consistency of the
playtstyle names.

feat: Change "ACO Cooperative" to "ACO Coop"

---

src/boost/teamwork.go

Increase the maximum farm capacity for 3 slot artifacts from 14,125,000,000
to 14,175,000,000. This change is necessary to accommodate the increased
production capabilities of the new 3 slot artifacts.

feat(teamwork): Increase max farm capacity for 3 slot artifacts

---

src/boost/contract.go

The changes made in this commit strip the Boost list style from the contract
and set the contract's style to banker style. This is done because a contract
that is a CRT (Continuous Running Tournament) is by definition a leaderboard
play style, and the Boost list style is not compatible with this.

feat(contract): strip Boost list style and set to banker style

---

.github/workflows/development.yml

Disables the test step in the development workflow and enables the
build step. This change is made to focus on the build process and
ensure that the application can be successfully compiled for the
target platforms.

feat: Disable test step and enable build step

---

.github/workflows/ci.yml

Disables the go test step in the CI workflow to
temporarily bypass the test suite while the team
investigates a recent regression.

feat: Disable go test in CI workflow

---

src/bottools/banners.go

Ensure the banner output directory exists before attempting to write
the banner image file. This prevents errors when the directory does
not exist.

feat: Ensure banner output directory exists

---

src/boost/teamwork.go
src/config/config.go

This change adds a new configuration option called `DevelopmentStaff` to
the `config.go` file. This option is a list of user IDs for development 
staff. This change is necessary to implement a new feature that allows 
only development staff to use a coop-id that starts with a '?' 
character.
The changes also include updating the `configStruct` and the `ReadConfig`
function to handle the new configuration option.

feat(config): Add DevelopmentStaff configuration

---

src/boost/teamwork.go

This commit introduces changes to the contract score calculation logic 
in the `teamwork.go` file. The main changes are:
1. Introduce a new variable `B` to store the uncapped buff time value.
2. Calculate the maximum contract score with current buffs and maximum Chicken Runs and Token Value.
3. Calculate the "sink" contract score with current buffs and maximum Chicken Runs but negative Token Value.
4. Calculate the contract score with Token Value met and Chicken Runs reduced by 1.
5. Calculate the contract score with no Token Value and Chicken Runs reduced by 1.
6. Calculate the minimum contract score with 0 Chicken Runs and 0 Token Value.
7. Store the calculated contract scores in an array for further processing.
These changes aim to provide a more comprehensive analysis of the contract …

feat: Calculate contract scores with different scenarios

---

src/boost/boost_draw.go

Adds the sort rate to the boost display in the `boost_draw.go` file.
This change allows users to see the sort rate for each boost, which is
an important piece of information when deciding which boosts to use.

feat: Add sort rate to boost display

---

src/boost/teamwork.go
src/ei/coop_status.go

The changes in this commit add the Unix timestamp to the data timestamp 
string in the `coop_status.go` file. This makes it easier to parse and 
use the timestamp information.
Additionally, in the `teamwork.go` file, a new feature is added to handle the case where the `coopID` starts with `**`. In this case, the function will search for files in the `ttbb-data` directory that match the `contractID` and `coopID` pattern, and return the list of matching filenames.

feat(coop-status): Add timestamp in Unix format to data timestamp

---

main.go
src/boost/boost.go
src/boost/boost_button_reactions.go
src/boost/boost_change.go
src/boost/boost_slashcmd.go
src/boost/contract.go

This commit adds a new command `/toggle-contract-pings` that allows 
users to toggle whether they receive pings for a contract they are part 
of. When enabled, the user will be added to the contract's role, and 
when disabled, the user will be removed from the role.
Additionally, this commit includes a change to the `DeleteContract` function
to also delete the contract's role when the contract is deleted.

feat(boost): Add toggle-contract-pings command

---

src/boost/contract.go

Adds a new admin choice name "TBone Alt" to the list of available
contract names. This change provides more options for admins to
choose from when creating new contracts.

feat(contract): add new admin choice name "TBone Alt"

---

src/boost/contract.go
src/ei/ei_data.go
src/events/datastore.go
src/events/periodicals.go
src/notok/notok.go

The changes in this commit focus on caching the team names for each 
contract in a separate map, which is then saved to disk and loaded on 
subsequent runs. This is done to improve performance and reduce the need
to repeatedly parse the contract descriptions to extract the team names.
The key changes are:
- A new `teamRoleMap` is created to store the cached team names, and a `currentTeamRoleMap` is used to track the current team names.
- The team names are loaded from disk if available, or generated and cached in `currentTeamRoleMap` if not.
- The `c.TeamNames` field is set based on the cached values or the newly generated ones.
- The `currentTeamRoleMap` is saved to disk at the end of the processing loop.
These changes should improve the overall performance of the application by reducing …

feat: Implement caching of contract team names

---

src/boost/teamwork.go

Adds the switch time to the production schedule output, in addition to the
finish time with one player switch. This provides more detailed information
about the production schedule to the user.

feat: Add switch time to production schedule output

---

main.go
src/boost/boost_admin.go

This change adds a new slash command `/list-roles` that allows admins to
display the contract roles and the channels they are used in. This
provides visibility into the contract role usage, which is helpful for
managing the bot's permissions and roles.
The key changes include:
- Add a new slash command definition in `SlashAdminListRoles`
- Implement the handler function `HandleAdminListRoles` to retrieve the
contract roles and display them in an ephemeral message
- Register the new slash command in the `globalCommands` and
`interactionHandlers` in `main.go`

feat: Add slash command to list contract roles

---

src/boost/boost_admin.go

The changes made in this commit are:
1. Removed the `adminPermission` variable assignment as it is no longer needed.
2. Removed the `DefaultMemberPermissions` field from the `discordgo.ApplicationCommand` struct as it is not required for the functionality of the slash command.
These changes were made to simplify the implementation of the `SlashAdminListRoles` function and remove unnecessary code.

feat(admin): Modify slash command to remove admin permission

---

src/boost/boost_import.go

Modifies the contract grade calculation logic in the `boost_import.go`
file. Removes the special case handling for the "housing-boom" contract
at grade 5, as it is no longer necessary. This simplifies the code and
makes the grade calculation more consistent across all contracts.

feat(boost): Adjust contract grade calculation logic

---

src/boost/boost_cooptval.go

- If there are no tokens sent or received in the contract, a message is displayed indicating this.
- The token value display logic is wrapped in an `else` block to ensure it is only executed when there are tokens to display.
- The formatting of the token value display remains the same, with the exception of the addition of the "No tokens sent or received in this contract." message.

feat: Improve token value display logic

---

src/boost/boost_button_reactions.go
src/boost/boost_menu.go

Adds a new "Grange" option to the boost menu that displays a list of
all Grange members, sorted by their join timestamp. This provides an
easy way for users to see who is part of the Grange and when they
joined.

feat(boost): Add Grange member list to boost menu

---

src/boost/boost.go
src/boost/boost_admin.go
src/boost/contract.go

diff --git a/src/boost/contract.go b/src/boost/contract.go
index 4d3d7d3..d4d4d4e 100644
--- a/src/boost/contract.go
+++ b/src/boost/contract.go
@@ -413,7 +413,7 @@ func generateContractName(roleNames []string) (string, []string) {
break
}
tryCount++
-		if tryCount == 28 && len(roleNames) == 30 {
+		if tryCount == 28 && len(roleNames) == 30 {
roleNames = randomThingNames // Reset the names to the fallback list
prefix = "Team "
}

feat(boost): Increase the maximum number of name retries

---

src/boost/estimate_time.go

Adds the contract duration to the output string, formatted using the
`bottools.FmtDuration` function. This provides a more complete
representation of the contract details to the user.

feat(estimate_time): Add contract duration to output

---

go.mod

The changes in this commit update the Go version from 1.24.6 to 1.25. This update is necessary to take advantage of the latest features and improvements in the Go programming language, which can enhance the overall performance and stability of the application.

feat: Update Go version to 1.25

---

src/boost/boost_reactions.go

The changes made in this commit improve the logic for advancing the boost
list. The key changes are:
- Active boosters must react with the boost icon (e.g. 🚀) when spending
tokens to boost, in order to advance the list. This ensures the active
booster explicitly indicates they have boosted.
- Multiple boost icon reactions from other participants in the contract
will also move the list to the next booster, in addition to the active
booster's reaction.
- This change applies to both the standard boost list and the banker-
controlled boost list.

feat(boost): Improve boost list advancement logic

---

src/bottools/app_emoji.go

Converts the emoji name to lowercase before creating the emoji in
Discord. This ensures that the emoji name is consistent with the
existing emoji names in the server.

feat(emoji): convert emoji name to lowercase

---

src/bottools/app_emoji.go

The changes made in this commit allow for the use of uppercase
characters in the names of emojis created in Discord. Previously,
the code was converting the emoji name to lowercase, which could
result in unexpected behavior or loss of information. By allowing
the original case to be preserved, this change improves the
flexibility and usability of the emoji creation functionality.

feat(emoji): Allow uppercase emoji names

---

src/boost/boost.go
src/boost/contract.go

The changes in this commit address the following:
1. Modify the token sending logic to only allow token sending when the contract
state is not `ContractStateCRT`.
2. Ensure that the interaction user is always included in the list of
progenitors, even if the list is already at the maximum size.

feat(boost): handle contract state for token sending

---

Dockerfile

Adds the `emoji` directory to the Docker container, allowing the
bot to access the necessary emoji files for its functionality.
This change ensures the bot can properly display emojis in its
responses.

feat(docker): Add emoji directory to container

---

src/boost/boost.go
src/boost/boost_handlers.go

The changes made in this commit focus on disabling the speedrun start button when the contract is full. The key changes are:
- The button is only enabled when the contract's order length is less than the coop size, or one less than the coop size.
- The `GetSignupComponents` function is called with `false` to get a disabled start button when the contract is full.
- The message editing logic is updated to only update the message when the contract is full or nearly full.
These changes ensure that the speedrun start button is properly disabled when the contract is full, providing a better user experience.

feat: Disable speedrun start button when contract is full

---

src/boost/boost.go

Adds a check to respect the contract's boost position when the contract
has the FastRun flag set. This ensures that the boost position is
correctly set for fast-run contracts, which may have a different boost
position than the default.

feat(boost): Respect contract boost position for fast-run contracts

---

src/boost/boost_slashcmd.go

Recalculates the token values for a boost contract after the estimated
duration has been modified. This ensures the token values are updated
correctly when the duration changes.

feat(boost): Recalculate token values after duration change

---

src/boost/contract.go

The changes in this commit improve the role name generation logic in the
`boost/contract.go` file. The key changes are:
- Create a list of unused role names by filtering out the existing roles
from the full list of role names.
- Shuffle the list of unused role names to ensure a random selection.
- Use the unused role names list instead of the full list of role names to
find an unused name.
- If the list of unused role names is exhausted, reset it to the fallback
list of random thing names and shuffle it.
- This change ensures that the role names are selected from the unused
names, reducing the likelihood of collisions and improving the overall
name generation process.

feat(boost/contract): Improve role name generation

---

src/events/periodicals.go

The changes update the ACO channel ID used for sending notifications. The
previous channel was for the Contracts version 2 project, but this has
been updated to use the Colleggtibles chat channel instead.

feat(events): update ACO channel for Colleggtibles

---

src/boost/boost.go
src/boost/boost_button_reactions.go
src/boost/boost_handlers.go
src/boost/contract.go

The changes in this commit add support for a new "Leaderboard" playstyle to the contract system. The key changes are:
- Uncomment the previously commented-out "Leaderboard" playstyle option in the contract configuration.
- Update the contract style handling to set the contract style to "Banker" when the playstyle is set to "Leaderboard".
- Add a new case in the `boost_button_reactions.go` file to handle the "Leaderboard" playstyle and display the appropriate Discord channel link.
- Update the `boost_handlers.go` file to include the "Leaderboard" playstyle option in the select menu.
These changes allow users to select the "Leaderboard" playstyle for their contracts, which will automatically configure the contract style to use the "Banker" style.

feat(contract): Add leaderboard playstyle and update handling

---

src/boost/boost.go
src/boost/boost_cooptval.go
src/bottools/tokens.go
src/track/track.go

The changes made in this commit are:
1. Updated the `BoostingSinkUserID` field in the `BankerInfo` struct to be more descriptive as "Boosting Sink User ID".
2. Removed the `TimeCRT` field from the `ContractInfo` struct as it was not being used.
3. Simplified the logic in the `ContractStateBanker` case by directly setting the `TimeBoosting` field to the current time, instead of checking if `TimeCRT` is zero.
4. Updated the `CalculateFutureTokenLogs` function to remove the `crtTime` parameter, as it is no longer needed.
These changes improve the clarity and simplify the code, making it easier to understand and maintain.

feat: Update Boosting Sink User ID and remove TimeCRT

---

src/boost/boost.go
src/boost/boost_speedrun.go
src/boost/contract.go
src/boost/message_redraw.go

The changes remove the `Speedrun` field from the contract struct and instead use the `ContractFlagBanker` flag to determine the contract style. This simplifies the code and makes it more flexible, as the contract style can now be determined based on the flags instead of a separate boolean field.
The changes also remove some commented-out code related to CRT settings, as these are no longer needed.

feat: remove speedrun mode and use contract flags instead

---

src/boost/boost_speedrun.go
src/boost/contract.go

The changes made in this commit update the contract style and boost order for contracts with a leaderboard play style. Specifically:
- The contract style is set to `ContractFlagBanker` for leaderboard play style contracts.
- The boost order is set to `ContractOrderTVal` for leaderboard play style contracts.
- These changes ensure that the contract style and boost order are properly configured for leaderboard play style contracts.

feat(boost): update contract style and boost order for leaderboard

---

src/ei/ei_api.go

Refactors the `printArchivedContracts` function to move it after the
`GetContractArchiveFromAPI` function. This improves the code organization
and makes the flow of the program more intuitive.

feat: Refactor archived contracts printing logic

---

src/boost/boost_handlers.go
src/boost/help.go

The changes remove the "Join w/Ping" button from the boost handlers. This button was not being used and was causing confusion for users, so it has been removed to simplify the interface.
The changes also update the help message to remove the reference to the "Join w/Ping" button, as it is no longer available.

feat(boost): remove join with ping button

---

src/boost/boost_draw.go

The changes add additional details about the banker's boost position for
active contracts. This information is only displayed for contracts in the
signup state, as the banker's role is only relevant during the boosting
phase. The changes ensure that the correct boost details are shown to
users, improving the overall user experience.

feat: Add banker boost details for active contracts

---

src/boost/boost_handlers.go

Adds a volunteer sink for all fastrun contracts, regardless of whether
they have a CRT or not. This ensures that all fastrun contracts have a
sink to handle their post-contract processing.

feat: Add volunteer sink for all fastrun contracts

---

src/boost/teamwork.go

Modify the logic for swapping SIAB artifacts to handle the
special case of the Compass artifact, which has 2 slots instead
of the usual 3 slots. Update the output message to reflect the
correct number of slots for the swapped artifact.

feat: Improve SIAB artifact swap logic

---

src/boost/siab.go

The changes remove a debug print statement that was printing the total contract duration. This print statement was not necessary for the functionality of the code and was removed to reduce clutter and improve the overall code readability.

feat(siab): Remove debug print statement for contract duration

---

main.go
src/boost/boost_import.go
src/boost/replay.go
src/bottools/discord.go
src/config/config.go
src/ei/ei_api.go
src/ei/ei_data.go
src/ei/ei_units.go
src/farmerstate/farmerstate.go

This commit introduces two main changes:
1. Implement a new function `getContractScoreEstimate` to calculate the estimated contract score (CXP) for contracts with version 2. This function takes into account various factors such as the contract grade, booster usage, SIAB, Deflector, Chicken Runs, and token sending/receiving patterns to provide a more accurate CXP estimate.
2. Modify the `GetContractArchiveFromAPI` and `printArchivedContracts` functions to download and display the archived contracts from the Egg Inc API. The archived contracts are now displayed in a formatted table, showing the contract ID, estimated CXP, maximum potential CXP, the gap between the two, and the percentage of the maximum potential achieved.
These changes aim to provide more accurate CXP estimates for active …

feat: Implement contract score estimation and display archived contracts

---

src/boost/replay.go
src/ei/ei_api.go

The changes made in this commit are focused on refactoring the `GetFirstContactFromAPI` and `GetContractArchiveFromAPI` functions in the `ei_api.go` file. The main changes are:
1. The `GetFirstContactFromAPI` function now returns an array of `LocalContract` instead of printing the archived contracts directly. This allows the caller to handle the data as needed.
2. The `GetContractArchiveFromAPI` function also now returns an array of `LocalContract` instead of printing the archived contracts.
3. Unnecessary imports and code have been removed to keep the file more concise.
These changes make the functions more modular and easier to use in other parts of the application.

feat: Refactor GetFirstContactFromAPI and GetContractArchiveFromAPI

---

src/boost/replay.go
src/config/encryption.go
src/ei/ei_api.go

This commit introduces several improvements to the `GetFirstContactFromAPI` and `GetContractArchiveFromAPI` functions:
1. Caching: The function now checks if a cached file exists for the given Discord ID. If the file is within 10 minutes old, it loads the data from the cache instead of making a new API request.
2. Encryption: The cached data is encrypted using the encryption key from the `config` package. This ensures that the sensitive Egg Inc user data is stored securely on the file system.
3. Fallback to API request: If no cached data is available or the cached data is too old, the function falls back to making a new API request and saves the response to the cache.
These changes improve the performance and security of the bot by reducing the number of API requests and protecting user …

feat(ei_api): Implement caching and encryption for Egg Inc API requests

---

src/boost/replay.go
src/config/config.go
src/ei/ei_api.go

The changes in this commit add functionality to generate an encryption key if it is missing in the config file. This is necessary for a few features that require encryption.
The key is generated using the `GenerateKey()` function and then encoded to a base64 string. The config file is then updated with the new key and written back to disk.
This ensures that the application has a valid encryption key available for use, even if it was not provided in the original config file.

feat: Generate encryption key if missing in config

---

main.go
src/boost/eggidmodal.go
src/boost/replay.go

Adds a new function `RequestEggIncIDModal` that sends a modal to the user
requesting their Egg Inc ID. This modal is used when the user's Egg Inc ID
is not found or is invalid.
The `HandleEggIDModalSubmit` function is also added to handle the submission
of the modal, validating the Egg Inc ID and storing the encrypted ID in the
user's settings.

feat: add modal for requesting Egg Inc ID

---

main.go

The "m_m_eggid" command has been renamed to "m_eggid" to simplify the
command naming convention. This change will make the codebase more
maintainable and easier to understand.

feat: Rename "m_m_eggid" command to "m_eggid"

---

.github/workflows/development.yml

Builds binaries for FreeBSD and Linux platforms, including amd64 and arm
architectures. Removes the `go telemetry off` command as it is no longer
necessary.

feat: Build binaries for FreeBSD and Linux

---

src/boost/replay.go

Adds a check to save user data to a file if the data is not cached and it
is okay to save the data. This ensures that user data is persisted to
disk for later retrieval.

feat: Save user data to file if not cached and okay to save

---

src/bottools/staabmia_link.go

This change adds a new `PlayerData` struct to the `staabmia_link.go` file,
which allows for the inclusion of player data in the generated staabmia
links. The `remDash` function has also been commented out, as it is no
longer needed.

feat: Add support for player data in staabmia link

---

src/boost/replay.go
src/boost/virtue.go

The changes made in this commit include:
1. Checking the CXP version and logging a message if it's not "cxp_v0_2_0". This is to ensure that contracts can only be evaluated for the correct version.
2. Adding a check to display ephemeral messages in the "#bot-commands" channel. This helps to keep the main channel clean and organized.
3. Refactoring the `getShiftCost` function to make it more reusable and easier to understand.
4. Improving the formatting and readability of the "Eggs of Virtue Helper" message.
5. Fixing a bug where the `futureEov` value was not being calculated correctly.
These changes aim to improve the overall stability and user experience of the application.

feat: Improve CXP version handling and ephemeral messages

---

src/boost/virtue.go

Optimize the calculation of `futureEov` by using a more efficient
subtraction operation instead of the previous `max()` function. This
change ensures that the `futureEov` value is correctly updated based on
the difference between `eovPending` and `eov`.

feat(virtue): Optimize EOV calculation

---

src/boost/siab.go
src/boost/teamwork.go

The changes in this commit adjust the calculation of the CR (Contribution Ratio) cap for
contracts with CxpVersion 1. For these contracts, the CR cap is set to the MaxCoopSize
minus 1, instead of the previous calculation based on contract duration. This ensures
that the CR cap is always one less than the MaxCoopSize for CxpVersion 1 contracts.

feat(contracts): Adjust CR cap for CxpVersion 1 contracts

---

src/boost/siab.go
src/boost/teamwork.go

The changes in this commit optimize the contract score calculation by:
- Removing the unnecessary `capCR` variable and directly using `eiContract.ChickenRuns`.
- Simplifying the calculation of `diffCR` by removing the division by `capCR`.
- Updating the loop that generates the contract score table to use `eiContract.ChickenRuns` directly.
- Updating the calls to `calculateChickenRunTeamwork` and `calculateTokenTeamwork` to use the correct values for `CR` and `T`.
These changes improve the readability and maintainability of the code, while also ensuring that the contract score calculation is accurate and up-to-date with the latest contract details.

feat(teamwork): Optimize contract score calculation

---

src/boost/virtue.go
src/ei/ei_data.go
src/ei/research.go

Adds a new internal hatchery sharing multiplier `colleggtiblesIHR` to the `ei_data.go` file. This multiplier is used in the calculation of the online and offline shipping rates in the `research.go` file.
The changes also include:
- Updating the shipping rate and egg laying rate formatting in the `virtue.go` file to improve readability.
- Increasing the safety limit for the shipping rate calculation loop from 10,000,000 minutes to 1,051,200 minutes (approximately 2 years).
- Adding a footer to the virtue report with the report run time and last sync time.

feat: Add internal hatchery sharing multiplier

---

src/boost/virtue.go

Updates the egg effects to display the art of the last fueled ship. If the
bot is in dev mode, it uses the dev art instead.

feat: update egg effects based on last fueled ship

---

src/boost/virtue.go
src/ei/research.go

The changes in this commit focus on the implementation of fuel rate calculation and display in the hatchery report. The key changes are:
1. Added a new variable `fuelingEnabled` to check if tank filling is enabled.
2. Calculated the `fuelRate` based on the egg laying rate and the flow percentage of artifacts.
3. Included the fuel rate in the hatchery report, displaying it alongside the egg laying and shipping rates.
4. Removed the commented-out code related to fuel rate, as it has now been implemented.
5. Simplified the hatchery report formatting by removing some unnecessary information.
The changes aim to provide a more comprehensive and informative hatchery report, including the fuel rate, which is an important metric for players to monitor.

feat(hatchery): Implement fuel rate calculation and display

---

src/boost/virtue.go
src/ei/research.go

The changes made in this commit include:
1. Updating the delivery time message in the `virtue.go` file to display "in more than a year" instead of "in more than 2 years".
2. Modifying the `research.go` file to increase the laying rate per step based on the population increase, instead of the delivery rate.
3. Reducing the safety time limit from 1,051,200 minutes (approximately 2 years) to 525,600 minutes (1 year) to prevent infinite loops.
These changes aim to improve the user experience by providing more accurate delivery time information and optimizing the research process.

feat(boost): Adjust delivery time message and increase laying rate

---

src/boost/virtue.go

Displays the artifact stats (SR, ELR, IHR, Hab) in a separate section
from the "Max Colleggtibles Assumed" message. This makes the artifact
stats more prominent and easier to read.

feat(virtue): Display artifact stats in separate section

---

src/boost/virtue.go

Adds a new `init()` function that builds a table of breakpoints for Truth
Eggs above 16. This table is used to calculate the required eggs laid for
Truth Eggs above 16.
The changes also remove the hardcoded breakpoint values for Truth Eggs
above 100q, as these can now be calculated using the new table.

feat(boost/virtue): Add TruthEggBreakpoints table

---

src/boost/contract_scores.go
src/boost/siab.go
src/boost/teamwork.go

This commit introduces changes to the contract score calculation logic:
1. Adds a new `calculateBuffTimeValue` function to compute the buff time value based on the contract version, segment duration, SIAB percentage, and Deflector percentage.
2. Introduces a new `calculateTeamworkB` function to compute the teamwork B score based on the contract version and buff time value.
3. Modifies the `calculateChickenRunTeamwork` function to handle the contract version-specific logic.
4. Updates the `calculateContractScore` function to use the new `getPredictedTeamwork` function, which considers the contract version when calculating the teamwork score.
5. Removes the cap on SIAB and Deflector percentages for CXP version 1 contracts, as they no longer have buff time value requirements.
These changes …

feat(contract_scores): Implement new buff time value and teamwork calculations

---

src/ei/ei_api.go

This change moves the JSON file writing for the backup data into a
separate goroutine, allowing the main function to return the backup
data more quickly without waiting for the file write to complete.
The redaction of the eiUserID in the JSON data is also preserved in
this change.

feat: Asynchronously write backup JSON file

---

src/boost/score_explorer.go

Adds a new chicken run option "CoopSize-1" to the `chickenRunsStr` array.
This allows players to select a chicken run value that is one less than the
maximum coop size, which can be useful in certain game scenarios.

feat(score_explorer): Add new chicken run option

---

src/boost/virtue.go

Optimize the calculation of offline eggs by using the elapsed time in
hours instead of seconds. This ensures that the offline egg production
is calculated correctly and matches the expected behavior.

feat: Optimize offline egg calculation

---

src/boost/virtue.go
src/ei/ei_api.go

The changes introduce a new boolean flag `onVirtueFarm` to track whether the current egg type is the "farm" egg. This flag is used to adjust the output formatting, specifically the display of shipping rate, egg laying rate, and fuel rate. The changes ensure that the output is formatted correctly when the player is on the Virtue Farm.

feat: Add onVirtueFarm flag and adjust output formatting

---

src/boost/virtue.go

Simplify the declaration of the `onVirtueFarm` variable by removing the
explicit boolean assignment. This makes the code more concise and
readable without changing the functionality.

feat: Simplify variable declaration in virtue.go

---

src/boost/virtue.go

This change adds logic to detect if the player is on the Virtue Farm based on the
egg type. If the egg type is between Curiosity and Kindness, the `onVirtueFarm`
flag is set to `true`. This information is used later in the code to handle
habitat and vehicle information.

feat: Add Virtue Farm detection logic

---

src/boost/boost_import.go
src/boost/estimate_time.go
src/ei/ei_data.go

This commit improves the contract score estimation logic in the `boost_import.go` file. The key changes are:
1. Removed the commented-out code that calculated the contract score with different teamwork multipliers, as the new logic supersedes this.
2. Introduced a `fairShare` variable to handle the different CXP version calculations. For CXP version 1, the fair share is set to 1.02, while for CXP version 2, it is set to 1.05.
3. Calculated the base contract score without any teamwork multipliers, and used this to compute the CXP run delta, which represents the CXP gained per chicken run.
4. Introduced a `CxpBuffOnly` field to store the contract score with only the buffs included, without any chicken runs.
5. Simplified the contract score estimation logic in the `estimate_time.go` file, …

feat(boost): improve contract score estimation

---

src/boost/score_explorer.go

This commit introduces several improvements to the score explorer feature:
1. Removes the hardcoded `fairShare` array and replaces it with a dynamic array that includes more granular values.
2. Changes the `FairShare` field in the `ScoreCalcParams` struct to be a `float64` instead of an `int`.
3. Replaces the static "Fair Share" button with a dynamic select menu that allows the user to choose from a range of fair share values.
4. Adds a deferred response to the interaction, displaying a "Processing request..." message while the score is being calculated.
5. Switches from using `InteractionRespond` to `FollowupMessageCreate` to send the final score explorer message, which allows for more flexibility in the message content.
These changes improve the user experience by providing more …

feat(score_explorer): Improve score explorer UI and functionality

---

src/boost/virtue.go

This change adds a new feature to calculate a recommended fuel rate when
fueling is disabled. The recommended fuel rate is determined by checking
if the egg laying rate is high enough over the shipping rate to enable
fueling at different tiers (10%, 50%, and 90%). The recommended fuel rate
is then displayed in the stats output.

feat(fueling): Implement recommended fuel rate calculation

---

src/boost/virtue.go

- Improve the formatting of the fuel rate display by moving the "**" characters to wrap the rate value instead of the unit.
- Update the mission end time display to use the mission's end time directly instead of calculating the remaining time.

feat(boost/virtue): Improve fuel rate display and mission end time

---

src/farmerstate/privacy.go

Deleting the ttbb-data/eiuserdata files when the user requests data 
deletion.

✨ feat(privacy): Remove user data files on privacy reset

---

src/boost/virtue.go

This PR fixes the /virtue command description in virtue.go.

fix: correct command description for /virtue
